"""Task 33: the `coag_mode` table, its captured golden, and the mask carrier.

Acceptance: byte-equal to the Fortran, masks exposed as static-shape traced
bools. Both halves are here, plus the evidence for the two claims the module
docstring makes that are not self-evident — that `coag_mode` is genuinely
setup-independent, and that enough `(imode, jmode)` pairs collide on a
destination for the accumulation order to matter.

Every test below names, in its docstring, the mutation that would make it fail;
several apply that mutation and check that it does. This file is written that
way because the repo's recurring defect is a test that cannot fail — nine found
across two reviews — and because this session already shipped a golden that was
silently the wrong data while every byte-equality test passed.

Only the two tests that rebuild the extension carry the `fortran` marker. The
golden is committed, so everything else runs in CI.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import jax
import jax.numpy as jnp
import numpy as np
import pytest

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "validation"))
import capture_coag_mode as capture  # noqa: E402

from glomap_jax.physics import modes  # noqa: E402
from glomap_jax.physics.coag_mode import (  # noqa: E402
    BRANCH_TAGS,
    COAG_MODE,
    COAG_MODE_FORTRAN,
    DERIVED_BRANCH_TAGS,
    SOLVECOAGNUCL_BRANCH_TAGS,
    CoagMasks,
    accumulation_order,
    destination,
    destination_census,
    full_table_census,
    source_pairs,
)

SOURCE = REPO / "fortran" / "src" / "ukca" / "ukca_mode_setup.F90"
GOLDEN = REPO / "tests" / "goldens" / "coagmode.f64.tables.npz"
SETUPS = (1, 2, 3, 4, 5, 6, 8)

# case -> the namelist that produced its branch golden.
CASES = {
    "boundary_layer": REPO / "fortran" / "namelists" / "boundary_layer.nml",
    "free_troposphere": REPO / "fortran" / "namelists" / "free_troposphere.nml",
    "marine_bcoc": REPO / "fortran" / "namelists" / "marine_bcoc.nml",
    "bl_nmts3": REPO / "inputs" / "namelists" / "bl_nmts3.nml",
}

# The three branch-dump sites that record one entry per (imode, jmode) pair for
# which `mtran` is written. `coag_insol_insol` is the ins-SOL block despite its
# name; the label is the committed overlay's and is not corrected here.
PAIR_SITES = ("coag_sol_sol", "coag_sol_insol", "coag_insol_insol")


@pytest.fixture(scope="module")
def golden():
    assert GOLDEN.is_file(), "run `python validation/capture_coag_mode.py`"
    return np.load(GOLDEN, allow_pickle=False)


@pytest.fixture(scope="module")
def source_text():
    return SOURCE.read_text(encoding="utf-8")


# ---------------------------------------------------------------------------
# The table against the vendored source.
# ---------------------------------------------------------------------------


def test_the_committed_table_matches_a_fresh_parse_of_the_fortran(source_text):
    """Fails if any digit of `_RESHAPE_SOURCE_ORDER` is edited, or if the block
    stops being regenerated after a vendored-tree update."""
    np.testing.assert_array_equal(COAG_MODE_FORTRAN, capture.parse_source(source_text))
    assert COAG_MODE_FORTRAN.dtype == np.int32


def test_the_emitted_literal_is_exactly_what_the_module_carries(source_text):
    """The block in `physics/coag_mode.py` is generated by
    `capture_coag_mode.py --emit-literal`; this is that claim, checked. Fails
    if someone reformats or hand-edits the block."""
    emitted = capture.emit_literal(capture.parse_source(source_text))
    module = (REPO / "src" / "glomap_jax" / "physics" / "coag_mode.py").read_text()
    assert emitted in module


def test_a_single_changed_digit_in_the_source_moves_the_parse(source_text):
    """The mutation test for the two above. Without it they could both be
    passing on a parser that returns a constant.

    Flips the last entry of the first RESHAPE line, 4 -> 5, and checks the
    parse follows it in exactly one place.
    """
    mutated, n = re.subn(
        r"(1, 2, 3, 4, 2, 3, )4, 4,",
        r"\g<1>4, 5,",
        source_text,
        count=1,
    )
    assert n == 1, "the mutation did not apply -- this test proves nothing as written"

    moved = capture.parse_source(mutated)
    differing = np.argwhere(moved != COAG_MODE_FORTRAN)
    assert differing.shape[0] == 1, f"expected 1 changed entry, got {differing.shape[0]}"
    # Source line 1 is coag_mode(1:8, 1), so entry 8 of it is coag_mode(8, 1).
    assert tuple(differing[0]) == (7, 0)
    with pytest.raises(AssertionError):
        np.testing.assert_array_equal(COAG_MODE_FORTRAN, moved)


def test_the_parser_refuses_a_source_with_no_declaration(source_text):
    """A regex that silently matches nothing is how the wrong golden ships."""
    with pytest.raises(AssertionError, match="found 0"):
        capture.parse_source(source_text.replace("coag_mode( nmodes, nmodes )", "xxx( 1, 1 )"))


def test_the_parser_refuses_a_source_with_two_declarations(source_text):
    """Taking the first of two matches would be a silent choice."""
    decl = re.search(capture._DECL, source_text).group(0)
    with pytest.raises(AssertionError, match="found 2"):
        capture.parse_source(source_text + "\n" + decl + "\n")


def test_the_parser_refuses_a_truncated_literal(source_text):
    """A line-based parser silently truncates a continued array to whatever
    fitted on the first line; this asserts the count instead."""
    mutated, n = re.subn(r"1, 2, 3, 4, 2, 3, 4, 4,\s*&\s*\n", "", source_text, count=1)
    assert n == 1
    with pytest.raises(AssertionError, match="parsed 56"):
        capture.parse_source(mutated)


def test_the_declaration_is_at_the_line_the_docstring_cites(source_text):
    """`ukca_mode_setup.F90:174`. Fails if the vendored tree is ever updated
    and the citation is not."""
    line = source_text.splitlines()[173]
    assert "coag_mode( nmodes, nmodes )" in line
    assert "PARAMETER" in line


def test_nothing_in_the_vendored_tree_assigns_coag_mode():
    """The setup-independence claim, made against the source text.

    Every mention of the name in `fortran/src/` must be the one declaration,
    the two lines of the single consumer, a `USE ... ONLY` import, or a
    comment. An assignment anywhere else would mean the table is configuration
    after all. Fails if a future vendored update adds one.
    """
    hits = []
    for path in sorted((REPO / "fortran" / "src").rglob("*.F90")):
        for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            if "coag_mode" in line:
                hits.append((path.name, lineno, line.strip()))

    code = [h for h in hits if not h[2].startswith("!")]
    declarations = [h for h in code if "PARAMETER" in h[2]]
    assert len(declarations) == 1, declarations
    assert declarations[0][0] == "ukca_mode_setup.F90"
    assert declarations[0][1] == 174

    consumers = {(h[0], h[1]) for h in code} - {(h[0], h[1]) for h in declarations}
    # The RESHAPE literal spans continuation lines that do not repeat the name,
    # so the only remaining code lines are the USE and the single call site.
    assert consumers == {
        ("ukca_coagwithnucl.F90", 152),  # USE ukca_mode_setup, ONLY: ... coag_mode
        ("ukca_coagwithnucl.F90", 534),  # mtrantoi(:,coag_mode(imode,jmode),icp) =
        ("ukca_coagwithnucl.F90", 535),  #      mtrantoi(:,coag_mode(imode,jmode),icp) +
    }, sorted(consumers)


# ---------------------------------------------------------------------------
# Properties of the table itself.
# ---------------------------------------------------------------------------


def test_the_zero_based_and_one_based_tables_agree():
    np.testing.assert_array_equal(COAG_MODE, COAG_MODE_FORTRAN - 1)
    assert COAG_MODE.min() == 0
    assert COAG_MODE.max() == modes.NMODES - 1


def test_the_tables_are_read_only():
    """They are module-level shared state. A caller that mutated one in place
    would change every later import in the process."""
    for table in (COAG_MODE, COAG_MODE_FORTRAN):
        with pytest.raises(ValueError):
            table[0, 0] = 99


def test_the_table_is_symmetric_which_is_why_no_test_can_catch_a_transpose():
    """Stated as a test so the limitation is recorded rather than assumed.

    `coag_mode(i,j) == coag_mode(j,i)` for all 64 entries, so a transposed
    transcription is byte-equal to the correct one and neither the source
    re-parse nor the f2py capture could distinguish them. If this ever fails,
    the port has gained a real check it did not have before — and every
    `(imode, jmode)` order in `coag_mode.py` needs re-deriving from the call
    site, because it was never pinned by data.
    """
    np.testing.assert_array_equal(COAG_MODE, COAG_MODE.T)


def test_the_diagonal_is_the_identity():
    """Intra-modal coagulation keeps its mass in the same mode. Not exercised
    by the scatter — `mtran(:,:,i,i)` is never written — but a table whose
    diagonal moved would mean the whole reading of it is wrong."""
    np.testing.assert_array_equal(np.diag(COAG_MODE), np.arange(modes.NMODES))


def test_the_full_table_census_is_what_the_docstring_says():
    """The number quoted in `coag_mode.py`, recomputed from committed data."""
    assert full_table_census() == {0: 1, 1: 7, 2: 13, 3: 27, 4: 1, 5: 3, 6: 5, 7: 7}
    assert sum(full_table_census().values()) == modes.NMODES**2


def test_destination_reads_the_call_sites_subscript_order():
    """`coag_mode(imode, jmode)` with `imode` the mode losing the mass."""
    assert destination(0, 4) == COAG_MODE[0, 4]
    # Nuc-sol coagulating with Ait-insol lands in Ait-sol (Fortran 1,5 -> 2).
    assert destination(0, 4) == 1
    # Anything with Cor-sol lands in Cor-sol.
    assert all(destination(i, 3) == 3 for i in range(modes.NMODES))


# ---------------------------------------------------------------------------
# The captured golden.
# ---------------------------------------------------------------------------


def test_the_golden_covers_every_supported_setup(golden):
    assert list(golden["_setups"]) == list(SETUPS)
    assert int(golden["_nmodes"]) == modes.NMODES
    for setup in SETUPS:
        assert f"s{setup}_coag_mode" in golden


def test_the_table_read_from_the_extension_matches_the_committed_one(golden):
    """Byte equality against the compiled Fortran, not against the source text.

    Fails if the Python table drifts from what gfortran actually built, which
    the source re-parse alone could not tell you.
    """
    np.testing.assert_array_equal(golden["coag_mode_noinit"], COAG_MODE_FORTRAN)
    for setup in SETUPS:
        np.testing.assert_array_equal(
            golden[f"s{setup}_coag_mode"], COAG_MODE_FORTRAN, err_msg=f"setup {setup}"
        )


def test_every_setup_read_the_same_table(golden):
    """The setup-independence claim, from the golden rather than from grep.

    Would fail if any `i_mode_setup` rebound `coag_mode`. Vacuous on its own —
    a capture that never varied the setup would also pass — which is what the
    next test exists to rule out.
    """
    tables = [golden[f"s{setup}_coag_mode"] for setup in SETUPS]
    tables.append(golden["coag_mode_noinit"])
    for other in tables[1:]:
        np.testing.assert_array_equal(tables[0], other)


def test_the_capture_actually_varied_the_setup(golden):
    """The anti-tautology guard.

    `coag_mode` being identical across setups is only evidence if the setups
    were actually different. The archive carries `mode`, `topmode` and `ncp`
    per setup for exactly this reason. Fails if the capture script's namelist
    replacement ever no-ops and every subprocess runs setup 1 — the failure
    mode this repo has already shipped once.
    """
    witnesses = {
        setup: (
            tuple(int(v) for v in golden[f"s{setup}_mode"]),
            int(golden[f"s{setup}_topmode"]),
            int(golden[f"s{setup}_ncp"]),
        )
        for setup in SETUPS
    }
    assert len(set(witnesses.values())) > 1, witnesses
    # Four distinct active-mode patterns across the seven setups.
    assert len({w[0] for w in witnesses.values()}) == 4
    active = {setup: sum(w[0]) for setup, w in witnesses.items()}
    assert active == {1: 4, 2: 5, 3: 4, 4: 5, 5: 4, 6: 2, 8: 7}


def test_the_captured_mode_flags_agree_with_the_ported_tables(golden):
    """Ties this archive to `physics/modes.py`, so the two cannot drift into
    disagreeing about which modes are on."""
    for setup in SETUPS:
        tables = modes.build(setup)
        np.testing.assert_array_equal(
            golden[f"s{setup}_mode"].astype(bool), tables.mode, err_msg=f"setup {setup}"
        )
        assert int(golden[f"s{setup}_topmode"]) == tables.topmode
        assert int(golden[f"s{setup}_ncp"]) == tables.ncp


# ---------------------------------------------------------------------------
# Which entries the scatter actually reaches.
# ---------------------------------------------------------------------------


def _setup_of(namelist: Path) -> int:
    text = namelist.read_text(encoding="utf-8")
    found = re.findall(r"^\s*i_mode_setup\s*=\s*(\d+)", text, flags=re.MULTILINE)
    assert len(found) == 1, f"{namelist.name}: {len(found)} i_mode_setup lines"
    # The switches that would change `topmode` or the active modes are not
    # overridden in any shipped namelist, so modes.build's defaults apply. If
    # one ever is, this assertion is where it surfaces rather than as a silently
    # wrong pair list.
    for switch in ("l_dust_mp_ageing", "l_radaer", "i_tune_bc"):
        assert switch not in text, f"{namelist.name} overrides {switch}"
    return int(found[0])


@pytest.mark.parametrize("case", sorted(CASES))
def test_source_pairs_match_the_committed_branch_goldens(case):
    """`source_pairs` reimplements `ukca_coagwithnucl`'s loop nest, and the
    branch dump recorded which `(imode, jmode)` the Fortran actually visited.

    This is the check that the loop bounds are right. Fails on an off-by-one in
    any of the three blocks — mutate `imode + 4` to `imode + 3` and
    `marine_bcoc` reports a pair the Fortran never visited.
    """
    archive = REPO / "tests" / "goldens" / f"{case}.f64.branches.npz"
    with np.load(archive, allow_pickle=False) as data:
        sites = [str(s) for s in data["site_levels"]]
        wanted = {sites.index(s) for s in PAIR_SITES if s in sites}
        keep = np.isin(data["site"], list(wanted))
        recorded = {(int(a) - 1, int(b) - 1) for a, b in zip(data["i1"][keep], data["i2"][keep])}

    tables = modes.build(_setup_of(CASES[case]))
    assert recorded == set(source_pairs(tables))


def test_the_branch_goldens_disagree_between_cases():
    """Guards the test above from passing on a comparison that is the same on
    both sides for a trivial reason. setup 1 visits 6 pairs, setup 2 visits 9;
    if those were equal the parametrisation would be measuring nothing."""
    counts = {case: len(source_pairs(modes.build(_setup_of(nml)))) for case, nml in CASES.items()}
    assert counts == {
        "boundary_layer": 6,
        "free_troposphere": 6,
        "bl_nmts3": 6,
        "marine_bcoc": 9,
    }


def test_source_pairs_never_repeat_and_never_touch_the_diagonal():
    """`mtran(:,:,i,j)` is written by exactly one block, so a repeat would mean
    two blocks overlap and the second would overwrite the first."""
    for setup in SETUPS:
        for dust in (False, True):
            pairs = source_pairs(modes.build(setup, l_dust_mp_ageing=dust))
            assert len(pairs) == len(set(pairs)), (setup, dust)
            assert all(i != j for i, j in pairs), (setup, dust)


def test_setup_six_reaches_no_pairs_at_all():
    """`duonly_2mode` activates only Acc-insol and Cor-insol. Neither is
    soluble, so the soluble blocks never run, and the insoluble block needs a
    soluble partner. Nothing is ever scattered."""
    tables = modes.build(6)
    assert list(np.flatnonzero(tables.mode)) == [5, 6]
    assert source_pairs(tables) == ()
    assert destination_census(tables) == {}


def test_the_per_setup_census_is_what_the_docstring_says():
    """Every number quoted in `coag_mode.py`'s scatter section, recomputed."""
    for setup in (1, 3, 5):
        assert destination_census(modes.build(setup)) == {1: 1, 2: 2, 3: 3}
    for setup in (2, 4, 8):
        assert destination_census(modes.build(setup)) == {1: 2, 2: 3, 3: 4}
    assert destination_census(modes.build(8, l_dust_mp_ageing=True)) == {1: 2, 2: 5, 3: 8}
    assert destination_census(modes.build(6)) == {}


def test_destinations_collide_so_the_scatter_must_accumulate():
    """The finding the port has to act on. If every destination took at most
    one pair, `.at[].set()` would do and the ordering question would not
    exist."""
    worst = max(
        max(destination_census(modes.build(s, l_dust_mp_ageing=d)).values(), default=0)
        for s in SETUPS
        for d in (False, True)
    )
    assert worst == 8
    reachable_by_the_box_model = max(
        max(destination_census(modes.build(s)).values(), default=0) for s in SETUPS
    )
    assert reachable_by_the_box_model == 4


def test_accumulation_order_is_the_fortran_loop_order():
    """`imode` outer then `jmode`, and every source pair accounted for exactly
    once. Fails if `accumulation_order` stops sorting."""
    for setup in SETUPS:
        tables = modes.build(setup, l_dust_mp_ageing=True)
        plan = accumulation_order(tables)
        flat = [pair for pairs in plan.values() for pair in pairs]
        assert sorted(flat) == sorted(source_pairs(tables))
        for dest, pairs in plan.items():
            assert list(pairs) == sorted(pairs), (setup, dest)
            assert all(destination(i, j) == dest for i, j in pairs)


def test_the_accumulation_order_is_not_an_academic_concern():
    """The float-associativity claim, measured rather than asserted.

    Eight terms into one destination is what setup 8 with dust ageing produces.
    Summed in Fortran order and in reverse they give two different doubles, so
    a `.at[].add()` whose order XLA chooses is a different answer, not a
    differently-spelled one. Fails only if float64 addition becomes
    associative.
    """
    terms = jnp.array([1.0, 1e-16, 1e-16, 1e-16, 1e-16, 1e-16, 1e-16, 1e-16], dtype=jnp.float64)

    forward = jnp.zeros((), dtype=jnp.float64)
    for term in terms:
        forward = forward + term
    backward = jnp.zeros((), dtype=jnp.float64)
    for term in terms[::-1]:
        backward = backward + term

    assert float(forward) != float(backward)
    # And the same through the mechanism the port will actually use.
    acc_f = jnp.zeros(1, dtype=jnp.float64)
    for term in terms:
        acc_f = acc_f.at[0].add(term)
    acc_b = jnp.zeros(1, dtype=jnp.float64)
    for term in terms[::-1]:
        acc_b = acc_b.at[0].add(term)
    assert float(acc_f[0]) != float(acc_b[0])


# ---------------------------------------------------------------------------
# The mask carrier.
# ---------------------------------------------------------------------------


def _masks(nbox: int = 5) -> CoagMasks:
    rng = np.random.default_rng(33)
    draw = lambda: jnp.asarray(rng.random(nbox) > 0.5)  # noqa: E731
    return CoagMasks(mask1=draw(), mask1a=draw(), mask2=draw(), mask3=draw(), mask4=draw())


def test_the_carrier_is_a_pytree_that_round_trips():
    """Fails if a field is dropped from the dataclass or marked static: both
    change the pytree structure, and `lax.scan` rejects a carry whose structure
    moves between iterations."""
    masks = _masks()
    leaves, treedef = jax.tree_util.tree_flatten(masks)
    assert len(leaves) == 5
    rebuilt = jax.tree_util.tree_unflatten(treedef, leaves)
    for name in ("mask1", "mask1a", "mask2", "mask3", "mask4"):
        np.testing.assert_array_equal(getattr(rebuilt, name), getattr(masks, name))


def test_the_masks_are_bool_and_share_one_static_shape():
    masks = _masks(7)
    masks.validate(nbox=7)
    assert masks.shape == (7,)
    assert all(jnp.result_type(getattr(masks, n)) == jnp.bool_ for n in ("mask1", "mask4"))


def test_validate_rejects_a_ragged_or_float_carrier():
    """The mutation: drop the `validate` body and both of these stop raising."""
    good = _masks(4)
    with pytest.raises(ValueError, match="share one shape"):
        CoagMasks(
            mask1=jnp.zeros(3, dtype=bool),
            mask1a=good.mask1a,
            mask2=good.mask2,
            mask3=good.mask3,
            mask4=good.mask4,
        ).validate()
    with pytest.raises(ValueError, match="must be bool"):
        CoagMasks(
            mask1=jnp.zeros(4),
            mask1a=good.mask1a,
            mask2=good.mask2,
            mask3=good.mask3,
            mask4=good.mask4,
        ).validate()
    with pytest.raises(ValueError, match="is not"):
        good.validate(nbox=9)


def test_the_shape_survives_vmap_as_a_scalar_per_parcel():
    """The whole point of "static shape". Under `vmap` each parcel sees `()`,
    identically for all five fields — which is what lets the same code run
    eagerly over `(nbox,)` and vmapped over parcels."""
    seen = []

    def per_parcel(masks: CoagMasks) -> CoagMasks:
        seen.append(masks.shape)
        masks.validate()
        return masks.narrow_mask1(masks.mask2)

    out = jax.vmap(per_parcel)(_masks(6))
    assert seen == [()]
    assert out.shape == (6,)


def test_a_mask_derived_trip_count_fails_under_vmap():
    """Why the rule is "mask the values, never the trip count", made
    executable. `jnp.nonzero` needs a concrete size; under `vmap` each parcel
    would want a different one, so it raises rather than quietly picking one.

    Fails if JAX ever starts accepting this — at which point the module
    docstring's justification needs rewriting, not deleting.
    """
    with pytest.raises(jax.errors.ConcretizationTypeError):
        jax.vmap(lambda m: jnp.nonzero(m)[0].sum())(jnp.array([[True, False], [True, True]]))


def test_the_carrier_works_as_a_lax_scan_carry_over_components():
    """`ukca_coagwithnucl.F90:567-570` narrows `mask1` in place across the
    `icp` loop, which is why CLAUDE.md lists that loop among the five that need
    a sequential scan. This is the carry that makes it expressible."""
    nbox, ncp = 4, 3
    keeps = jnp.array(
        [
            [True, True, True, True],
            [True, False, True, True],
            [True, True, False, True],
        ]
    )

    def step(carry: CoagMasks, keep):
        carry = carry.narrow_mask1(keep)
        return carry, carry.mask1

    start = CoagMasks(
        mask1=jnp.ones(nbox, dtype=bool),
        mask1a=jnp.ones(nbox, dtype=bool),
        mask2=jnp.zeros(nbox, dtype=bool),
        mask3=jnp.zeros(nbox, dtype=bool),
        mask4=jnp.zeros(nbox, dtype=bool),
    )
    final, per_step = jax.lax.scan(step, start, keeps)

    assert per_step.shape == (ncp, nbox)
    np.testing.assert_array_equal(final.mask1, np.array([True, False, False, True]))
    # The other four fields come through untouched, which is what makes the
    # carry structure stable.
    np.testing.assert_array_equal(final.mask1a, start.mask1a)


def test_narrow_mask1_only_ever_narrows():
    """The mutation: `&` -> `|` in `narrow_mask1`. A box excluded for one
    component must stay excluded for every later one; widening it would
    resurrect a mode whose number was just zeroed."""
    masks = _masks(64)
    narrowed = masks.narrow_mask1(masks.mask2)
    assert bool(jnp.all(narrowed.mask1 <= masks.mask1))
    assert int(jnp.sum(narrowed.mask1)) < int(jnp.sum(masks.mask1))


def test_effective_mask4_is_the_only_form_the_science_uses():
    """`mask4` carries a stale `bterm` where `mask2` is false. The raw field is
    kept because the gate-0 dump records it raw; `effective_mask4` is what the
    physics may read."""
    masks = _masks(64)
    np.testing.assert_array_equal(
        masks.effective_mask4, np.asarray(masks.mask4) & np.asarray(masks.mask2)
    )
    # And the distinction is not vacuous on this sample.
    assert int(jnp.sum(masks.mask4 != masks.effective_mask4)) > 0


def test_every_declared_branch_tag_exists_in_the_committed_goldens():
    """Ties `BRANCH_TAGS` to the gate-0 dump. Exact set equality, so a renamed
    site, a dropped `branch_mask` call or a tag invented here all fail.

    The union over the four cases is used because setup 1 never reaches the
    insoluble sites — that is the reason `marine_bcoc` is in the fixture set.
    """
    recorded: set[tuple[str, str]] = set()
    for case in CASES:
        archive = REPO / "tests" / "goldens" / f"{case}.f64.branches.npz"
        with np.load(archive, allow_pickle=False) as data:
            sites = [str(s) for s in data["site_levels"]]
            tags = [str(t) for t in data["tag_levels"]]
            for site_i, tag_i in zip(data["site"], data["tag"]):
                site, tag = sites[site_i], tags[tag_i]
                if site.startswith("coag_") and tag not in SOLVECOAGNUCL_BRANCH_TAGS:
                    recorded.add((site, tag))

    declared = {pair for pairs in BRANCH_TAGS.values() for pair in pairs}
    declared |= set(DERIVED_BRANCH_TAGS)
    assert recorded == declared


def test_mask1_is_dumped_on_both_sides_of_the_in_place_narrowing():
    """`mask1_entry` and `mask1_after` are not duplicates: they straddle the
    narrowing, which is what makes it observable. Fails if one is dropped from
    `BRANCH_TAGS` as redundant."""
    assert ("coag_reset", "mask1_entry") in BRANCH_TAGS["mask1"]
    assert ("coag_reset", "mask1_after") in BRANCH_TAGS["mask1"]
    assert ("coag_reset", "mdcp_neg") in DERIVED_BRANCH_TAGS


# ---------------------------------------------------------------------------
# Against the live Fortran. Skipped without a toolchain.
# ---------------------------------------------------------------------------

fortran_only = pytest.mark.fortran


@fortran_only
def test_the_extension_agrees_with_the_committed_table():
    """Gate A, live: the same read the golden was captured from. Catches a
    vendored-tree change that the committed golden predates."""
    extension = REPO / "validation" / "f2py"
    if not list(extension.glob("glomap_f2py*.so")):
        pytest.skip("run ./validation/build_f2py.sh")
    record = capture.capture_one(None)
    np.testing.assert_array_equal(np.array(record["coag_mode"], dtype=np.int32), COAG_MODE_FORTRAN)
    np.testing.assert_array_equal(np.array(record["coag_dest"], dtype=np.int32), COAG_MODE_FORTRAN)
    assert record["guards_fired"] == 3
