"""Generated by `validation/extract_ageing_literals.py`. Do not edit.

`ukca_ageing`'s 21 budget write sites, parsed out of the Fortran.

    (imode, tmode, icp, budget, kind)   all 1-based

`kind` is `totage` for `totage(icp)*f_mm(icp)` -- the soluble material that
condensed or coagulated onto the insoluble mode -- and `naged` for
`naged*md(jl,imode,icp)`, the insoluble mode's own mass travelling with the
particles. 21 sites, 20 distinct names: `nmasagedocintr52` takes both,
because organic carbon is a condensable and a primary insoluble component.
"""

from __future__ import annotations

#: (imode, tmode, icp, budget, kind), in source order.
AGEING_BUDGET_SITES = (
    (5, 2, 1, "nmasagedsuintr52", "totage"),
    (5, 2, 3, "nmasagedocintr52", "totage"),
    (5, 2, 6, "nmasagedsointr52", "totage"),
    (5, 2, 2, "nmasagedbcintr52", "naged"),
    (5, 2, 3, "nmasagedocintr52", "naged"),
    (5, 2, 10, "nmasagedmpintr52", "naged"),
    (6, 3, 1, "nmasagedsuintr63", "totage"),
    (6, 3, 3, "nmasagedocintr63", "totage"),
    (6, 3, 6, "nmasagedsointr63", "totage"),
    (6, 3, 5, "nmasagedduintr63", "naged"),
    (6, 3, 10, "nmasagedmpintr63", "naged"),
    (7, 4, 1, "nmasagedsuintr74", "totage"),
    (7, 4, 3, "nmasagedocintr74", "totage"),
    (7, 4, 6, "nmasagedsointr74", "totage"),
    (7, 4, 5, "nmasagedduintr74", "naged"),
    (7, 4, 10, "nmasagedmpintr74", "naged"),
    (8, 4, 1, "nmasagedsuintr84", "totage"),
    (8, 4, 3, "nmasagedocintr84", "totage"),
    (8, 4, 6, "nmasagedsointr84", "totage"),
    (8, 4, 5, "nmasagedduintr84", "naged"),
    (8, 4, 10, "nmasagedmpintr84", "naged"),
)
