"""Generated by `validation/extract_binapara_literals.py`. Do not edit.

`ukca_binapara`'s Vehkamaki (2002) coefficients: 113 literals across four
expressions, machine-extracted and never retyped.

Each expression is an ORDERED tuple of `(sign, coefficient, factors,
over_termx)`. The order is the Fortran's, and it is load-bearing: Fortran
sums left to right, so regrouping the terms is algebraically identical and
numerically different.
"""

from __future__ import annotations

TERMX_TERMS = (
    ("+", 0.7409967177282139, (), False),
    ("-", 0.002663785665140117, ("tdegk",), False),
    ("+", 0.002010478847383187, ("logrh",), False),
    ("-", 0.0001832894131464668, ("tdegk", "logrh"), False),
    ("+", 0.001574072538464286, ("logrh2",), False),
    ("-", 0.00001790589121766952, ("tdegk", "logrh2"), False),
    ("+", 0.0001844027436573778, ("logrh3",), False),
    ("-", 1.503452308794887e-6, ("tdegk", "logrh3"), False),
    ("-", 0.003499978417957668, ("logh2so4",), False),
    ("+", 0.0000504021689382576, ("tdegk", "logh2so4"), False),
)

JVEH_TERMS = (
    ("+", 0.1430901615568665, (), False),
    ("+", 2.219563673425199, ("tdegk",), False),
    ("-", 0.02739106114964264, ("tdegk2",), False),
    ("+", 0.00007228107239317088, ("tdegk3",), False),
    ("+", 5.91822263375044, (), True),
    ("+", 0.1174886643003278, ("logrh",), False),
    ("+", 0.4625315047693772, ("tdegk", "logrh"), False),
    ("-", 0.01180591129059253, ("tdegk2", "logrh"), False),
    ("+", 0.0000404196487152575, ("tdegk3", "logrh"), False),
    ("+", 15.79628615047088, ("logrh",), True),
    ("-", 0.215553951893509, ("logrh2",), False),
    ("-", 0.0810269192332194, ("tdegk", "logrh2"), False),
    ("+", 0.001435808434184642, ("tdegk2", "logrh2"), False),
    ("-", 4.775796947178588e-6, ("tdegk3", "logrh2"), False),
    ("-", 2.912974063702185, ("logrh2",), True),
    ("-", 3.588557942822751, ("logrh3",), False),
    ("+", 0.04950795302831703, ("tdegk", "logrh3"), False),
    ("-", 0.0002138195118737068, ("tdegk2", "logrh3"), False),
    ("+", 3.108005107949533e-7, ("tdegk3", "logrh3"), False),
    ("-", 0.02933332747098296, ("logrh3",), True),
    ("+", 1.145983818561277, ("logh2so4",), False),
    ("-", 0.6007956227856778, ("tdegk", "logh2so4"), False),
    ("+", 0.00864244733283759, ("tdegk2", "logh2so4"), False),
    ("-", 0.00002289467254710888, ("tdegk3", "logh2so4"), False),
    ("-", 8.44984513869014, ("logh2so4",), True),
    ("+", 2.158548369286559, ("logrh", "logh2so4"), False),
    ("+", 0.0808121412840917, ("tdegk", "logrh", "logh2so4"), False),
    ("-", 0.0004073815255395214, ("tdegk2", "logrh", "logh2so4"), False),
    ("-", 4.019572560156515e-7, ("tdegk3", "logrh", "logh2so4"), False),
    ("+", 0.7213255852557236, ("logrh", "logh2so4"), True),
    ("+", 1.62409850488771, ("logrh2", "logh2so4"), False),
    ("-", 0.01601062035325362, ("tdegk", "logrh2", "logh2so4"), False),
    ("+", 0.00003771238979714162, ("tdegk2", "logrh2", "logh2so4"), False),
    ("+", 3.217942606371182e-8, ("tdegk3", "logrh2", "logh2so4"), False),
    ("-", 0.01132550810022116, ("logrh2", "logh2so4"), True),
    ("+", 9.71681713056504, ("logh2so42",), False),
    ("-", 0.1150478558347306, ("tdegk", "logh2so42"), False),
    ("+", 0.0001570982486038294, ("tdegk2", "logh2so42"), False),
    ("+", 4.009144680125015e-7, ("tdegk3", "logh2so42"), False),
    ("+", 0.7118597859976135, ("logh2so42",), True),
    ("-", 1.056105824379897, ("logrh", "logh2so42"), False),
    ("+", 0.00903377584628419, ("tdegk", "logrh", "logh2so42"), False),
    ("-", 0.00001984167387090606, ("tdegk2", "logrh", "logh2so42"), False),
    ("+", 2.460478196482179e-8, ("tdegk3", "logrh", "logh2so42"), False),
    ("-", 0.05790872906645181, ("logrh", "logh2so42"), True),
    ("-", 0.1487119673397459, ("logh2so43",), False),
    ("+", 0.002835082097822667, ("tdegk", "logh2so43"), False),
    ("-", 9.24618825471694e-6, ("tdegk2", "logh2so43"), False),
    ("+", 5.004267665960894e-9, ("tdegk3", "logh2so43"), False),
    ("-", 0.01270805101481648, ("logh2so43",), True),
)

NTOT_TERMS = (
    ("-", 0.002954125078716302, (), False),
    ("-", 0.0976834264241286, ("tdegk",), False),
    ("+", 0.001024847927067835, ("tdegk2",), False),
    ("-", 2.186459697726116e-6, ("tdegk3",), False),
    ("-", 0.1017165718716887, (), True),
    ("-", 0.002050640345231486, ("logrh",), False),
    ("-", 0.007585041382707174, ("tdegk", "logrh"), False),
    ("+", 0.0001926539658089536, ("tdegk2", "logrh"), False),
    ("-", 6.70429719683894e-7, ("tdegk3", "logrh"), False),
    ("-", 0.2557744774673163, ("logrh",), True),
    ("+", 0.003223076552477191, ("logrh2",), False),
    ("+", 0.000852636632240633, ("tdegk", "logrh2"), False),
    ("-", 0.00001547571354871789, ("tdegk2", "logrh2"), False),
    ("+", 5.666608424980593e-8, ("tdegk3", "logrh2"), False),
    ("+", 0.03384437400744206, ("logrh2",), True),
    ("+", 0.04743226764572505, ("logrh3",), False),
    ("-", 0.0006251042204583412, ("tdegk", "logrh3"), False),
    ("+", 2.650663328519478e-6, ("tdegk2", "logrh3"), False),
    ("-", 3.674710848763778e-9, ("tdegk3", "logrh3"), False),
    ("-", 0.0002672510825259393, ("logrh3",), True),
    ("-", 0.01252108546759328, ("logh2so4",), False),
    ("+", 0.005806550506277202, ("tdegk", "logh2so4"), False),
    ("-", 0.0001016735312443444, ("tdegk2", "logh2so4"), False),
    ("+", 2.881946187214505e-7, ("tdegk3", "logh2so4"), False),
    ("+", 0.0942243379396279, ("logh2so4",), True),
    ("-", 0.0385459592773097, ("logrh", "logh2so4"), False),
    ("-", 0.0006723156277391984, ("tdegk", "logrh", "logh2so4"), False),
    ("+", 2.602884877659698e-6, ("tdegk2", "logrh", "logh2so4"), False),
    ("+", 1.194163699688297e-8, ("tdegk3", "logrh", "logh2so4"), False),
    ("-", 0.00851515345806281, ("logrh", "logh2so4"), True),
    ("-", 0.01837488495738111, ("logrh2", "logh2so4"), False),
    ("+", 0.0001720723574407498, ("tdegk", "logrh2", "logh2so4"), False),
    ("-", 3.717657974086814e-7, ("tdegk2", "logrh2", "logh2so4"), False),
    ("-", 5.148746022615196e-10, ("tdegk3", "logrh2", "logh2so4"), False),
    ("+", 0.0002686602132926594, ("logrh2", "logh2so4"), True),
    ("-", 0.06199739728812199, ("logh2so42",), False),
    ("+", 0.000906958053583576, ("tdegk", "logh2so42"), False),
    ("-", 9.11727926129757e-7, ("tdegk2", "logh2so42"), False),
    ("-", 5.367963396508457e-9, ("tdegk3", "logh2so42"), False),
    ("-", 0.007742343393937707, ("logh2so42",), True),
    ("+", 0.0121827103101659, ("logrh", "logh2so42"), False),
    ("-", 0.0001066499571188091, ("tdegk", "logrh", "logh2so42"), False),
    ("+", 2.534598655067518e-7, ("tdegk2", "logrh", "logh2so42"), False),
    ("-", 3.635186504599571e-10, ("tdegk3", "logrh", "logh2so42"), False),
    ("+", 0.0006100650851863252, ("logrh", "logh2so42"), True),
    ("+", 0.0003201836700403512, ("logh2so43",), False),
    ("-", 0.0000174761713262546, ("tdegk", "logh2so43"), False),
    ("+", 6.065037668052182e-8, ("tdegk2", "logh2so43"), False),
    ("-", 1.421771723004557e-11, ("tdegk3", "logh2so43"), False),
    ("+", 0.0001357509859501723, ("logh2so43",), True),
)

RC_TERMS = (
    ("-", 1.6524245, (), False),
    ("+", 0.42316402, ("termx(jl)",), False),
    ("+", 0.33466487, ("ntot(jl)",), False),
)

#: `WHERE` bounds applied to the inputs before any logarithm (`:106-118`).
CLAMPS = {
    "t": (190.15, 300.15),
    "rh": (0.0001, 1.0),
    "h2so4": (10000.0, 100000000000.0),
}

#: The post-exponential rules at `:249-283`.
LIMITS = {
    "ntot_min": 4.0,
    "t_cold": 195.15,
    "j_cold": 100000.0,
    "j_floor": 1e-07,
    "j_ceiling": 10000000000.0,
}
