"""Generated by `validation/extract_coagwithnucl_literals.py`. Do not edit.

`ukca_coagwithnucl`'s budget write sites: one row per guarded
accumulation of `mtran` into `bud_aer_mas`, parsed out of the Fortran.

    (imode, jmode, icp, budget)   all 1-based, as the Fortran declares them

The extractor asserts that each name's `intr<i><j>` suffix and component
tag agree with the guard it sits inside, and that the `mtran` component
subscript is the same `cp_XX` the `icp` guard tests -- the two are written
independently in the source and a divergence would bank one component's
transfer against another's diagnostic.
"""

from __future__ import annotations

#: (imode, jmode, icp, budget), in source order.
COAG_BUDGET_SITES = (
    (1, 2, 1, "nmascoagsuintr12"),
    (1, 2, 3, "nmascoagocintr12"),
    (1, 2, 6, "nmascoagsointr12"),
    (1, 3, 1, "nmascoagsuintr13"),
    (1, 3, 3, "nmascoagocintr13"),
    (1, 3, 6, "nmascoagsointr13"),
    (1, 4, 1, "nmascoagsuintr14"),
    (1, 4, 3, "nmascoagocintr14"),
    (1, 4, 6, "nmascoagsointr14"),
    (1, 5, 1, "nmascoagsuintr15"),
    (1, 5, 3, "nmascoagocintr15"),
    (1, 5, 6, "nmascoagsointr15"),
    (1, 6, 1, "nmascoagsuintr16"),
    (1, 6, 3, "nmascoagocintr16"),
    (1, 6, 6, "nmascoagsointr16"),
    (1, 7, 1, "nmascoagsuintr17"),
    (1, 7, 3, "nmascoagocintr17"),
    (1, 7, 6, "nmascoagsointr17"),
    (1, 8, 1, "nmascoagsuintr18"),
    (1, 8, 3, "nmascoagocintr18"),
    (1, 8, 6, "nmascoagsointr18"),
    (2, 3, 1, "nmascoagsuintr23"),
    (2, 3, 2, "nmascoagbcintr23"),
    (2, 3, 3, "nmascoagocintr23"),
    (2, 3, 6, "nmascoagsointr23"),
    (2, 3, 8, "nmascoagntintr23"),
    (2, 3, 7, "nmascoagnhintr23"),
    (2, 3, 10, "nmascoagmpintr23"),
    (2, 4, 1, "nmascoagsuintr24"),
    (2, 4, 2, "nmascoagbcintr24"),
    (2, 4, 3, "nmascoagocintr24"),
    (2, 4, 6, "nmascoagsointr24"),
    (2, 4, 8, "nmascoagntintr24"),
    (2, 4, 7, "nmascoagnhintr24"),
    (2, 4, 10, "nmascoagmpintr24"),
    (3, 4, 1, "nmascoagsuintr34"),
    (3, 4, 2, "nmascoagbcintr34"),
    (3, 4, 3, "nmascoagocintr34"),
    (3, 4, 4, "nmascoagssintr34"),
    (3, 4, 6, "nmascoagsointr34"),
    (3, 4, 5, "nmascoagduintr34"),
    (3, 4, 8, "nmascoagntintr34"),
    (3, 4, 7, "nmascoagnhintr34"),
    (3, 4, 9, "nmascoagnnintr34"),
    (3, 4, 10, "nmascoagmpintr34"),
    (5, 3, 2, "nmascoagbcintr53"),
    (5, 3, 3, "nmascoagocintr53"),
    (5, 3, 10, "nmascoagmpintr53"),
    (5, 4, 2, "nmascoagbcintr54"),
    (5, 4, 3, "nmascoagocintr54"),
    (5, 4, 10, "nmascoagmpintr54"),
    (6, 4, 5, "nmascoagduintr64"),
    (6, 4, 10, "nmascoagmpintr64"),
)
