"""Generated by `validation/extract_conden_literals.py`. Do not edit.

`ukca_conden`'s 30 budget write sites, parsed out of the Fortran. Each row
is one `WHERE` block of the second mode loop:

    imode     the soluble mode whose block the site sits in (1-based)
    icp       the component the guard tests (1-based)
    sec_orgi  True for the `nmascondoci*` spellings, used only in the
              `jv == msec_orgi` arm
    kind      soluble / insoluble / super_coarse_insoluble, i.e. mask3,
              mask3i, mask4i
    nc_mode   the mode whose `nc` the delta is taken from (1-based)
    budget    the `bud_aer_mas` name accumulated
    ageterm   the `ageterm1` ordinal, 0 for none. NOT the index the
              source writes: it names a SOLUBLE mode PARAMETER standing
              in for an ordinal over the insoluble axis, and the
              extractor asserts `ageterm == nc_mode - 4` and stores the
              ordinal.

There are 30 rows and 29 distinct sites: `:576-602` is the same block
twice (issue #29), and both are kept because the Fortran runs both and
`bud_aer_mas` accumulates.
"""

from __future__ import annotations

#: (imode, icp, sec_orgi, kind, nc_mode, budget, ageterm), in source order.
WRITE_SITES = (
    (1, 1, False, "soluble", 1, "nmascondsunucsol", 0),
    (1, 3, True, "soluble", 1, "nmascondocinucsol", 0),
    (1, 3, False, "soluble", 1, "nmascondocnucsol", 0),
    (1, 6, False, "soluble", 1, "nmascondsonucsol", 0),
    (2, 1, False, "soluble", 2, "nmascondsuaitsol", 0),
    (2, 1, False, "insoluble", 5, "nmascondsuaitins", 1),
    (2, 3, True, "soluble", 2, "nmascondociaitsol", 0),
    (2, 3, False, "soluble", 2, "nmascondocaitsol", 0),
    (2, 3, True, "insoluble", 5, "nmascondociaitins", 1),
    (2, 3, False, "insoluble", 5, "nmascondocaitins", 1),
    (2, 6, False, "soluble", 2, "nmascondsoaitsol", 0),
    (2, 6, False, "insoluble", 5, "nmascondsoaitins", 1),
    (3, 1, False, "soluble", 3, "nmascondsuaccsol", 0),
    (3, 1, False, "insoluble", 6, "nmascondsuaccins", 2),
    (3, 3, True, "soluble", 3, "nmascondociaccsol", 0),
    (3, 3, False, "soluble", 3, "nmascondocaccsol", 0),
    (3, 3, False, "insoluble", 6, "nmascondocaccins", 2),
    (3, 3, False, "insoluble", 6, "nmascondocaccins", 2),
    (3, 6, False, "soluble", 3, "nmascondsoaccsol", 0),
    (3, 6, False, "insoluble", 6, "nmascondsoaccins", 2),
    (4, 1, False, "soluble", 4, "nmascondsucorsol", 0),
    (4, 1, False, "insoluble", 7, "nmascondsucorins", 3),
    (4, 1, False, "super_coarse_insoluble", 8, "nmascondsusupins", 4),
    (4, 3, True, "soluble", 4, "nmascondocicorsol", 0),
    (4, 3, False, "soluble", 4, "nmascondoccorsol", 0),
    (4, 3, False, "insoluble", 7, "nmascondoccorins", 3),
    (4, 3, False, "super_coarse_insoluble", 8, "nmascondocsupins", 4),
    (4, 6, False, "soluble", 4, "nmascondsocorsol", 0),
    (4, 6, False, "insoluble", 7, "nmascondsocorins", 3),
    (4, 6, False, "super_coarse_insoluble", 8, "nmascondsosupins", 4),
)

#: Sites the Fortran executes twice. Issue #29.
DUPLICATED = ("nmascondocaccins",)
