"""Gas-phase index tables, extracted from `ukca_setup_indices.F90`.

GENERATED -- do not edit. Regenerate with::

    python validation/extract_gas_literals.py

`tests/test_gas_indices.py` re-runs the extraction and compares, so an edit
here fails rather than silently diverging from the vendored Fortran.

Indices are as the Fortran writes them: **1-based, with 0 meaning absent**.
`physics/gas_indices.py` converts to 0-based and maps absent to -1.

Literals only. `nadvg`, `ntrag` and `condensable` are derived and are
recomputed there, because recomputing them is what makes this a port.
"""

GAS_LITERALS = {
    "derived": ["nadvg", "ntrag", "condensable"],
    "groups": {
        "budget": [
            "ndmsemoc",
            "ndmstend",
            "nso2eman",
            "nso2embm",
            "nso2emvl",
            "nso2tend",
            "nso2ddep",
            "nso2wdep",
            "nh2so4tend",
            "nh2so4ddep",
            "ncoseman",
            "ncosemoc",
            "ncostend",
            "ncs2eman",
            "ncs2emoc",
            "ncs2tend",
            "ndmsotend",
            "ndmsoddep",
            "nmsatend",
            "nmsaddep",
            "nterp_em",
            "nterp_tend",
            "nterp_ddep",
            "nsorg_tend",
            "nsorg_ddep",
            "nsorg_wdep",
        ],
        "count": ["nchemg", "ichem", "noffox", "nbudchem", "gasbudget", "ngasbudget"],
        "reaction": [
            "iohdms1",
            "iohdms2",
            "ino3dms",
            "idmsooh1",
            "idmsooh2",
            "ics2oh",
            "ih2soh",
            "icosoh",
        ],
        "s0": [
            "mox",
            "mnox",
            "mn2o5",
            "mhno4",
            "mhno3",
            "mh2o2",
            "mch4",
            "mco",
            "mch2o",
            "mmhp",
            "mhono",
            "mc2h6",
            "metooh",
            "mmecho",
            "mpan",
            "mc3h8",
            "mpnooh",
            "mpiooh",
            "metcho",
            "mme2co",
            "mmecoh",
            "mppan",
            "mmeno3",
            "moxs",
            "mnoys",
            "misop",
            "mc2h4",
            "mc2h2",
            "misooh",
            "mison",
            "mmacr",
            "mmacrooh",
            "mmpan",
            "mhacet",
            "mmgly",
            "mnald",
            "mhcooh",
            "mmeco3h",
            "mmeco2h",
            "mmeoh",
            "mnh3",
            "msotwo",
            "mmesme",
            "mh2so4",
            "mdmso",
            "mmsa",
            "mcs2",
            "mh2s",
            "mcos",
            "mmonoter",
            "msec_org",
            "msec_orgi",
            "mh2o2f",
            "mq3d",
            "mpt",
        ],
        "st": [
            "no",
            "no1d",
            "no3",
            "nno",
            "nno3",
            "nno2",
            "nn2o5",
            "nhno4",
            "nhno3",
            "noh",
            "nho2",
            "nh2o2",
            "nch4",
            "nco",
            "nch2o",
            "nmeoo",
            "nh2o",
            "nmhp",
            "nhono",
            "nc2h6",
            "netoo",
            "netooh",
            "nmecho",
            "nmeco3",
            "npan",
            "nc3h8",
            "npnoo",
            "npioo",
            "npnooh",
            "npiooh",
            "netcho",
            "netco3",
            "nme2co",
            "nmecoo",
            "nmecoh",
            "nppan",
            "nmeno3",
            "nos",
            "no1ds",
            "no3s",
            "nnoxs",
            "nhno3s",
            "nnoys",
            "nisop",
            "nc2h4",
            "nc2h2",
            "niso2",
            "nisooh",
            "nison",
            "nmacr",
            "nmacro2",
            "nmacrooh",
            "nmpan",
            "nhacet",
            "nmgly",
            "nnald",
            "nhcooh",
            "nmeco3h",
            "nmeco2h",
            "nmeoh",
            "nnh3",
            "nsotwo",
            "nmesme",
            "nh2so4",
            "ndmso",
            "nmsa",
            "ncs2",
            "nh2s",
            "ncos",
            "nmonoter",
            "nsec_org",
            "nh2o2f",
            "no3f",
            "nohf",
            "nno3f",
            "nq3d",
            "npt",
        ],
    },
    "nchemgmax": 50,
    "routines": {
        "ukca_indices_nochem": {
            "arrays": {
                "condensable_choice": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                "dimen": [
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                ],
                "mm_gas": [
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                ],
            },
            "scalars": {
                "gasbudget": 0,
                "ichem": 0,
                "icosoh": 0,
                "ics2oh": 0,
                "idmsooh1": 0,
                "idmsooh2": 0,
                "ih2soh": 0,
                "ino3dms": 0,
                "iohdms1": 0,
                "iohdms2": 0,
                "mc2h2": 0,
                "mc2h4": 0,
                "mc2h6": 0,
                "mc3h8": 0,
                "mch2o": 0,
                "mch4": 0,
                "mco": 0,
                "mcos": 0,
                "mcs2": 0,
                "mdmso": 0,
                "metcho": 0,
                "metooh": 0,
                "mh2o2": 0,
                "mh2o2f": 0,
                "mh2s": 0,
                "mh2so4": 0,
                "mhacet": 0,
                "mhcooh": 0,
                "mhno3": 0,
                "mhno4": 0,
                "mhono": 0,
                "mison": 0,
                "misooh": 0,
                "misop": 0,
                "mmacr": 0,
                "mmacrooh": 0,
                "mme2co": 0,
                "mmecho": 0,
                "mmeco2h": 0,
                "mmeco3h": 0,
                "mmecoh": 0,
                "mmeno3": 0,
                "mmeoh": 0,
                "mmesme": 0,
                "mmgly": 0,
                "mmhp": 0,
                "mmonoter": 0,
                "mmpan": 0,
                "mmsa": 0,
                "mn2o5": 0,
                "mnald": 0,
                "mnh3": 0,
                "mnox": 0,
                "mnoys": 0,
                "mox": 0,
                "moxs": 0,
                "mpan": 0,
                "mpiooh": 0,
                "mpnooh": 0,
                "mppan": 0,
                "mpt": 2,
                "mq3d": 1,
                "msec_org": 0,
                "msec_orgi": 0,
                "msotwo": 0,
                "nbudchem": 0,
                "nc2h2": 0,
                "nc2h4": 0,
                "nc2h6": 0,
                "nc3h8": 0,
                "nch2o": 0,
                "nch4": 0,
                "nchemg": 0,
                "nco": 0,
                "ncos": 0,
                "ncoseman": 0,
                "ncosemoc": 0,
                "ncostend": 0,
                "ncs2": 0,
                "ncs2eman": 0,
                "ncs2emoc": 0,
                "ncs2tend": 0,
                "ndmsemoc": 0,
                "ndmso": 0,
                "ndmsoddep": 0,
                "ndmsotend": 0,
                "ndmstend": 0,
                "netcho": 0,
                "netco3": 0,
                "netoo": 0,
                "netooh": 0,
                "ngasbudget": 0,
                "nh2o": 0,
                "nh2o2": 0,
                "nh2o2f": 0,
                "nh2s": 0,
                "nh2so4": 0,
                "nh2so4ddep": 0,
                "nh2so4tend": 0,
                "nhacet": 0,
                "nhcooh": 0,
                "nhno3": 0,
                "nhno3s": 0,
                "nhno4": 0,
                "nho2": 0,
                "nhono": 0,
                "niso2": 0,
                "nison": 0,
                "nisooh": 0,
                "nisop": 0,
                "nmacr": 0,
                "nmacro2": 0,
                "nmacrooh": 0,
                "nme2co": 0,
                "nmecho": 0,
                "nmeco2h": 0,
                "nmeco3": 0,
                "nmeco3h": 0,
                "nmecoh": 0,
                "nmecoo": 0,
                "nmeno3": 0,
                "nmeoh": 0,
                "nmeoo": 0,
                "nmesme": 0,
                "nmgly": 0,
                "nmhp": 0,
                "nmonoter": 0,
                "nmpan": 0,
                "nmsa": 0,
                "nmsaddep": 0,
                "nmsatend": 0,
                "nn2o5": 0,
                "nnald": 0,
                "nnh3": 0,
                "nno": 0,
                "nno2": 0,
                "nno3": 0,
                "nno3f": 0,
                "nnoxs": 0,
                "nnoys": 0,
                "no": 0,
                "no1d": 0,
                "no1ds": 0,
                "no3": 0,
                "no3f": 0,
                "no3s": 0,
                "noffox": 0,
                "noh": 0,
                "nohf": 0,
                "nos": 0,
                "npan": 0,
                "npioo": 0,
                "npiooh": 0,
                "npnoo": 0,
                "npnooh": 0,
                "nppan": 0,
                "npt": 2,
                "nq3d": 1,
                "nsec_org": 0,
                "nso2ddep": 0,
                "nso2eman": 0,
                "nso2embm": 0,
                "nso2emvl": 0,
                "nso2tend": 0,
                "nso2wdep": 0,
                "nsorg_ddep": 0,
                "nsorg_tend": 0,
                "nsorg_wdep": 0,
                "nsotwo": 0,
                "nterp_ddep": 0,
                "nterp_em": 0,
                "nterp_tend": 0,
            },
        },
        "ukca_indices_orgv1_soto3": {
            "arrays": {
                "condensable_choice": [
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    3,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                "dimen": [
                    0.0,
                    0.0,
                    4.5e-10,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    4.5e-10,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                ],
                "mm_gas": [
                    0.064,
                    0.062,
                    0.098,
                    0.078,
                    0.096,
                    0.076,
                    0.034,
                    0.06,
                    0.136,
                    0.15,
                    0.034,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                ],
            },
            "scalars": {
                "gasbudget": 0,
                "ichem": 1,
                "icosoh": 7,
                "ics2oh": 5,
                "idmsooh1": 0,
                "idmsooh2": 3,
                "ih2soh": 6,
                "ino3dms": 4,
                "iohdms1": 1,
                "iohdms2": 2,
                "mc2h2": 0,
                "mc2h4": 0,
                "mc2h6": 0,
                "mc3h8": 0,
                "mch2o": 0,
                "mch4": 0,
                "mco": 0,
                "mcos": 8,
                "mcs2": 6,
                "mdmso": 4,
                "metcho": 0,
                "metooh": 0,
                "mh2o2": 0,
                "mh2o2f": 11,
                "mh2s": 7,
                "mh2so4": 3,
                "mhacet": 0,
                "mhcooh": 0,
                "mhno3": 0,
                "mhno4": 0,
                "mhono": 0,
                "mison": 0,
                "misooh": 0,
                "misop": 0,
                "mmacr": 0,
                "mmacrooh": 0,
                "mme2co": 0,
                "mmecho": 0,
                "mmeco2h": 0,
                "mmeco3h": 0,
                "mmecoh": 0,
                "mmeno3": 0,
                "mmeoh": 0,
                "mmesme": 2,
                "mmgly": 0,
                "mmhp": 0,
                "mmonoter": 9,
                "mmpan": 0,
                "mmsa": 5,
                "mn2o5": 0,
                "mnald": 0,
                "mnh3": 0,
                "mnox": 0,
                "mnoys": 0,
                "mox": 0,
                "moxs": 0,
                "mpan": 0,
                "mpiooh": 0,
                "mpnooh": 0,
                "mppan": 0,
                "mpt": 13,
                "mq3d": 12,
                "msec_org": 10,
                "msec_orgi": 0,
                "msotwo": 1,
                "nbudchem": 26,
                "nc2h2": 0,
                "nc2h4": 0,
                "nc2h6": 0,
                "nc3h8": 0,
                "nch2o": 0,
                "nch4": 0,
                "nchemg": 11,
                "nco": 0,
                "ncos": 8,
                "ncoseman": 11,
                "ncosemoc": 12,
                "ncostend": 13,
                "ncs2": 6,
                "ncs2eman": 14,
                "ncs2emoc": 15,
                "ncs2tend": 16,
                "ndmsemoc": 1,
                "ndmso": 4,
                "ndmsoddep": 18,
                "ndmsotend": 17,
                "ndmstend": 2,
                "netcho": 0,
                "netco3": 0,
                "netoo": 0,
                "netooh": 0,
                "ngasbudget": 8,
                "nh2o": 0,
                "nh2o2": 0,
                "nh2o2f": 11,
                "nh2s": 7,
                "nh2so4": 3,
                "nh2so4ddep": 10,
                "nh2so4tend": 9,
                "nhacet": 0,
                "nhcooh": 0,
                "nhno3": 0,
                "nhno3s": 0,
                "nhno4": 0,
                "nho2": 0,
                "nhono": 0,
                "niso2": 0,
                "nison": 0,
                "nisooh": 0,
                "nisop": 0,
                "nmacr": 0,
                "nmacro2": 0,
                "nmacrooh": 0,
                "nme2co": 0,
                "nmecho": 0,
                "nmeco2h": 0,
                "nmeco3": 0,
                "nmeco3h": 0,
                "nmecoh": 0,
                "nmecoo": 0,
                "nmeno3": 0,
                "nmeoh": 0,
                "nmeoo": 0,
                "nmesme": 2,
                "nmgly": 0,
                "nmhp": 0,
                "nmonoter": 9,
                "nmpan": 0,
                "nmsa": 5,
                "nmsaddep": 20,
                "nmsatend": 19,
                "nn2o5": 0,
                "nnald": 0,
                "nnh3": 0,
                "nno": 0,
                "nno2": 0,
                "nno3": 0,
                "nno3f": 14,
                "nnoxs": 0,
                "nnoys": 0,
                "no": 0,
                "no1d": 0,
                "no1ds": 0,
                "no3": 0,
                "no3f": 12,
                "no3s": 0,
                "noffox": 3,
                "noh": 0,
                "nohf": 13,
                "nos": 0,
                "npan": 0,
                "npioo": 0,
                "npiooh": 0,
                "npnoo": 0,
                "npnooh": 0,
                "nppan": 0,
                "npt": 16,
                "nq3d": 15,
                "nsec_org": 10,
                "nso2ddep": 7,
                "nso2eman": 3,
                "nso2embm": 4,
                "nso2emvl": 5,
                "nso2tend": 6,
                "nso2wdep": 8,
                "nsorg_ddep": 25,
                "nsorg_tend": 24,
                "nsorg_wdep": 26,
                "nsotwo": 1,
                "nterp_ddep": 23,
                "nterp_em": 21,
                "nterp_tend": 22,
            },
        },
        "ukca_indices_orgv1_soto6": {
            "arrays": {
                "condensable_choice": [
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    6,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                "dimen": [
                    0.0,
                    0.0,
                    4.5e-10,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    4.5e-10,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                ],
                "mm_gas": [
                    0.064,
                    0.062,
                    0.098,
                    0.078,
                    0.096,
                    0.076,
                    0.034,
                    0.06,
                    0.136,
                    0.15,
                    0.034,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                ],
            },
            "scalars": {
                "gasbudget": 0,
                "ichem": 1,
                "icosoh": 7,
                "ics2oh": 5,
                "idmsooh1": 0,
                "idmsooh2": 3,
                "ih2soh": 6,
                "ino3dms": 4,
                "iohdms1": 1,
                "iohdms2": 2,
                "mc2h2": 0,
                "mc2h4": 0,
                "mc2h6": 0,
                "mc3h8": 0,
                "mch2o": 0,
                "mch4": 0,
                "mco": 0,
                "mcos": 8,
                "mcs2": 6,
                "mdmso": 4,
                "metcho": 0,
                "metooh": 0,
                "mh2o2": 0,
                "mh2o2f": 11,
                "mh2s": 7,
                "mh2so4": 3,
                "mhacet": 0,
                "mhcooh": 0,
                "mhno3": 0,
                "mhno4": 0,
                "mhono": 0,
                "mison": 0,
                "misooh": 0,
                "misop": 0,
                "mmacr": 0,
                "mmacrooh": 0,
                "mme2co": 0,
                "mmecho": 0,
                "mmeco2h": 0,
                "mmeco3h": 0,
                "mmecoh": 0,
                "mmeno3": 0,
                "mmeoh": 0,
                "mmesme": 2,
                "mmgly": 0,
                "mmhp": 0,
                "mmonoter": 9,
                "mmpan": 0,
                "mmsa": 5,
                "mn2o5": 0,
                "mnald": 0,
                "mnh3": 0,
                "mnox": 0,
                "mnoys": 0,
                "mox": 0,
                "moxs": 0,
                "mpan": 0,
                "mpiooh": 0,
                "mpnooh": 0,
                "mppan": 0,
                "mpt": 13,
                "mq3d": 12,
                "msec_org": 10,
                "msec_orgi": 0,
                "msotwo": 1,
                "nbudchem": 26,
                "nc2h2": 0,
                "nc2h4": 0,
                "nc2h6": 0,
                "nc3h8": 0,
                "nch2o": 0,
                "nch4": 0,
                "nchemg": 11,
                "nco": 0,
                "ncos": 8,
                "ncoseman": 11,
                "ncosemoc": 12,
                "ncostend": 13,
                "ncs2": 6,
                "ncs2eman": 14,
                "ncs2emoc": 15,
                "ncs2tend": 16,
                "ndmsemoc": 1,
                "ndmso": 4,
                "ndmsoddep": 18,
                "ndmsotend": 17,
                "ndmstend": 2,
                "netcho": 0,
                "netco3": 0,
                "netoo": 0,
                "netooh": 0,
                "ngasbudget": 8,
                "nh2o": 0,
                "nh2o2": 0,
                "nh2o2f": 11,
                "nh2s": 7,
                "nh2so4": 3,
                "nh2so4ddep": 10,
                "nh2so4tend": 9,
                "nhacet": 0,
                "nhcooh": 0,
                "nhno3": 0,
                "nhno3s": 0,
                "nhno4": 0,
                "nho2": 0,
                "nhono": 0,
                "niso2": 0,
                "nison": 0,
                "nisooh": 0,
                "nisop": 0,
                "nmacr": 0,
                "nmacro2": 0,
                "nmacrooh": 0,
                "nme2co": 0,
                "nmecho": 0,
                "nmeco2h": 0,
                "nmeco3": 0,
                "nmeco3h": 0,
                "nmecoh": 0,
                "nmecoo": 0,
                "nmeno3": 0,
                "nmeoh": 0,
                "nmeoo": 0,
                "nmesme": 2,
                "nmgly": 0,
                "nmhp": 0,
                "nmonoter": 9,
                "nmpan": 0,
                "nmsa": 5,
                "nmsaddep": 20,
                "nmsatend": 19,
                "nn2o5": 0,
                "nnald": 0,
                "nnh3": 0,
                "nno": 0,
                "nno2": 0,
                "nno3": 0,
                "nno3f": 14,
                "nnoxs": 0,
                "nnoys": 0,
                "no": 0,
                "no1d": 0,
                "no1ds": 0,
                "no3": 0,
                "no3f": 12,
                "no3s": 0,
                "noffox": 3,
                "noh": 0,
                "nohf": 13,
                "nos": 0,
                "npan": 0,
                "npioo": 0,
                "npiooh": 0,
                "npnoo": 0,
                "npnooh": 0,
                "nppan": 0,
                "npt": 16,
                "nq3d": 15,
                "nsec_org": 10,
                "nso2ddep": 7,
                "nso2eman": 3,
                "nso2embm": 4,
                "nso2emvl": 5,
                "nso2tend": 6,
                "nso2wdep": 8,
                "nsorg_ddep": 25,
                "nsorg_tend": 24,
                "nsorg_wdep": 26,
                "nsotwo": 1,
                "nterp_ddep": 23,
                "nterp_em": 21,
                "nterp_tend": 22,
            },
        },
        "ukca_indices_sv1": {
            "arrays": {
                "condensable_choice": [
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                "dimen": [
                    0.0,
                    0.0,
                    4.5e-10,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                ],
                "mm_gas": [
                    0.064,
                    0.062,
                    0.098,
                    0.078,
                    0.096,
                    0.076,
                    0.034,
                    0.06,
                    0.034,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                ],
            },
            "scalars": {
                "gasbudget": 0,
                "ichem": 1,
                "icosoh": 7,
                "ics2oh": 5,
                "idmsooh1": 0,
                "idmsooh2": 3,
                "ih2soh": 6,
                "ino3dms": 4,
                "iohdms1": 1,
                "iohdms2": 2,
                "mc2h2": 0,
                "mc2h4": 0,
                "mc2h6": 0,
                "mc3h8": 0,
                "mch2o": 0,
                "mch4": 0,
                "mco": 0,
                "mcos": 8,
                "mcs2": 6,
                "mdmso": 4,
                "metcho": 0,
                "metooh": 0,
                "mh2o2": 0,
                "mh2o2f": 9,
                "mh2s": 7,
                "mh2so4": 3,
                "mhacet": 0,
                "mhcooh": 0,
                "mhno3": 0,
                "mhno4": 0,
                "mhono": 0,
                "mison": 0,
                "misooh": 0,
                "misop": 0,
                "mmacr": 0,
                "mmacrooh": 0,
                "mme2co": 0,
                "mmecho": 0,
                "mmeco2h": 0,
                "mmeco3h": 0,
                "mmecoh": 0,
                "mmeno3": 0,
                "mmeoh": 0,
                "mmesme": 2,
                "mmgly": 0,
                "mmhp": 0,
                "mmonoter": 0,
                "mmpan": 0,
                "mmsa": 5,
                "mn2o5": 0,
                "mnald": 0,
                "mnh3": 0,
                "mnox": 0,
                "mnoys": 0,
                "mox": 0,
                "moxs": 0,
                "mpan": 0,
                "mpiooh": 0,
                "mpnooh": 0,
                "mppan": 0,
                "mpt": 11,
                "mq3d": 10,
                "msec_org": 0,
                "msec_orgi": 0,
                "msotwo": 1,
                "nbudchem": 20,
                "nc2h2": 0,
                "nc2h4": 0,
                "nc2h6": 0,
                "nc3h8": 0,
                "nch2o": 0,
                "nch4": 0,
                "nchemg": 9,
                "nco": 0,
                "ncos": 8,
                "ncoseman": 11,
                "ncosemoc": 12,
                "ncostend": 13,
                "ncs2": 6,
                "ncs2eman": 14,
                "ncs2emoc": 15,
                "ncs2tend": 16,
                "ndmsemoc": 1,
                "ndmso": 4,
                "ndmsoddep": 18,
                "ndmsotend": 17,
                "ndmstend": 2,
                "netcho": 0,
                "netco3": 0,
                "netoo": 0,
                "netooh": 0,
                "ngasbudget": 8,
                "nh2o": 0,
                "nh2o2": 0,
                "nh2o2f": 9,
                "nh2s": 7,
                "nh2so4": 3,
                "nh2so4ddep": 10,
                "nh2so4tend": 9,
                "nhacet": 0,
                "nhcooh": 0,
                "nhno3": 0,
                "nhno3s": 0,
                "nhno4": 0,
                "nho2": 0,
                "nhono": 0,
                "niso2": 0,
                "nison": 0,
                "nisooh": 0,
                "nisop": 0,
                "nmacr": 0,
                "nmacro2": 0,
                "nmacrooh": 0,
                "nme2co": 0,
                "nmecho": 0,
                "nmeco2h": 0,
                "nmeco3": 0,
                "nmeco3h": 0,
                "nmecoh": 0,
                "nmecoo": 0,
                "nmeno3": 0,
                "nmeoh": 0,
                "nmeoo": 0,
                "nmesme": 2,
                "nmgly": 0,
                "nmhp": 0,
                "nmonoter": 0,
                "nmpan": 0,
                "nmsa": 5,
                "nmsaddep": 20,
                "nmsatend": 19,
                "nn2o5": 0,
                "nnald": 0,
                "nnh3": 0,
                "nno": 0,
                "nno2": 0,
                "nno3": 0,
                "nno3f": 11,
                "nnoxs": 0,
                "nnoys": 0,
                "no": 0,
                "no1d": 0,
                "no1ds": 0,
                "no3": 0,
                "no3f": 0,
                "no3s": 0,
                "noffox": 2,
                "noh": 0,
                "nohf": 10,
                "nos": 0,
                "npan": 0,
                "npioo": 0,
                "npiooh": 0,
                "npnoo": 0,
                "npnooh": 0,
                "nppan": 0,
                "npt": 13,
                "nq3d": 12,
                "nsec_org": 0,
                "nso2ddep": 7,
                "nso2eman": 3,
                "nso2embm": 4,
                "nso2emvl": 5,
                "nso2tend": 6,
                "nso2wdep": 8,
                "nsorg_ddep": 0,
                "nsorg_tend": 0,
                "nsorg_wdep": 0,
                "nsotwo": 1,
                "nterp_ddep": 0,
                "nterp_em": 0,
                "nterp_tend": 0,
            },
        },
    },
    "setup_routine": {
        1: "ukca_indices_sv1",
        2: "ukca_indices_orgv1_soto3",
        3: "ukca_indices_orgv1_soto3",
        4: "ukca_indices_orgv1_soto6",
        5: "ukca_indices_orgv1_soto6",
        6: "ukca_indices_nochem",
        8: "ukca_indices_orgv1_soto3",
    },
}
