"""Generated by `validation/extract_remode_literals.py`. Do not edit.

`ukca_remode`'s merge budget write sites, one row each:

    (imode, jmode, icp, budget)   all 1-based; jmode is always imode+1

The extractor asserts each name's `intr<i><j>` suffix and component tag
against the `imode ==` block it sits in.
"""

from __future__ import annotations

#: (imode, jmode, icp, budget), in source order.
MERGE_BUDGET_SITES = (
    (1, 2, 1, "nmasmergsuintr12"),
    (1, 2, 3, "nmasmergocintr12"),
    (1, 2, 6, "nmasmergsointr12"),
    (2, 3, 1, "nmasmergsuintr23"),
    (2, 3, 2, "nmasmergbcintr23"),
    (2, 3, 3, "nmasmergocintr23"),
    (2, 3, 6, "nmasmergsointr23"),
    (2, 3, 8, "nmasmergntintr23"),
    (2, 3, 7, "nmasmergnhintr23"),
    (2, 3, 10, "nmasmergmpintr23"),
    (3, 4, 1, "nmasmergsuintr34"),
    (3, 4, 2, "nmasmergbcintr34"),
    (3, 4, 3, "nmasmergocintr34"),
    (3, 4, 4, "nmasmergssintr34"),
    (3, 4, 6, "nmasmergsointr34"),
    (3, 4, 8, "nmasmergntintr34"),
    (3, 4, 7, "nmasmergnhintr34"),
    (3, 4, 9, "nmasmergnnintr34"),
    (3, 4, 10, "nmasmergmpintr34"),
)
