"""Generated by `validation/extract_vapour_literals.py`. Do not edit.

`ukca_vapour.F90`'s PARAMETERs, live path only. The Ayers fit
coefficients and the three stratospheric density tables.
"""

from __future__ import annotations

XSB_EPS = 1e-06
P0 = 101325.0
KS1 = -21.661
KS2 = 2724.2
KS3 = 51.81
KS4 = -15732.0
KS5 = 47.004
KS6 = -6969.0
KS7 = -4.6183
BMINATM = 2e-08
BMAXATM = 2e-06

# Weight-percent H2SO4 the density table is tabulated at (:90).
PERCENT = (40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95)

# Density at 253 K, kg m-3 (:98), and its per-Kelvin slope (:94).
DATA253 = (
    1333.8,
    1381.1,
    1431.0,
    1483.3,
    1537.3,
    1592.4,
    1647.6,
    1701.6,
    1753.0,
    1800.1,
    1840.9,
    1873.2,
)
K_DIFF = (
    0.8,
    0.82,
    0.84,
    0.86,
    0.87,
    0.89,
    0.92,
    0.95,
    0.98,
    1.02,
    1.06,
    1.1,
)
