#!/usr/bin/env python3
"""Render `figures/report.html` from the extracted data.

    python figures/extract_figure_data.py
    python figures/measure_hazards.py
    python figures/make_report.py

Self-contained: the JSON is embedded and the charts are inline SVG built by a
little vanilla JS, so the page has no external dependency and can be published
as-is. Regenerate it whenever the goldens move.
"""

from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE / "report.html"

HEAD = """<title>GLOMAP-JAX Validation</title>
<style>
  :root {
    color-scheme: light;
    --surface: #fcfcfb;
    --panel: #ffffff;
    --ink: #0b0b0b;
    --ink-2: #52514e;
    --ink-3: #83817a;
    --rule: #e5e4df;
    --grid: #eeede8;
    --s1: #2a78d6;
    --s2: #eb6834;
    --s3: #1baf7a;
    --s4: #eda100;
    --critical: #d03b3b;
    --good: #0ca30c;
  }
  @media (prefers-color-scheme: dark) {
    :root:not([data-theme="light"]) {
      color-scheme: dark;
      --surface: #1a1a19; --panel: #212120; --ink: #ffffff; --ink-2: #c3c2b7;
      --ink-3: #8a8981; --rule: #333331; --grid: #2a2a28;
      --s1: #3987e5; --s2: #d95926; --s3: #199e70; --s4: #c98500;
      --critical: #d03b3b; --good: #0ca30c;
    }
  }
  :root[data-theme="dark"] {
    color-scheme: dark;
    --surface: #1a1a19; --panel: #212120; --ink: #ffffff; --ink-2: #c3c2b7;
    --ink-3: #8a8981; --rule: #333331; --grid: #2a2a28;
    --s1: #3987e5; --s2: #d95926; --s3: #199e70; --s4: #c98500;
    --critical: #d03b3b; --good: #0ca30c;
  }
  body {
    margin: 0; padding: 2.5rem 1.5rem 5rem; background: var(--surface); color: var(--ink);
    font: 15px/1.6 ui-sans-serif, -apple-system, "Segoe UI", system-ui, sans-serif;
  }
  .wrap { max-width: 62rem; margin: 0 auto; }
  h1 { font-size: 1.85rem; line-height: 1.2; margin: 0 0 .35rem; letter-spacing: -.02em; }
  .sub { color: var(--ink-2); margin: 0 0 2.5rem; }
  h2 { font-size: 1.15rem; margin: 3rem 0 .3rem; letter-spacing: -.01em; }
  .lede { color: var(--ink-2); margin: 0 0 1.25rem; max-width: 46rem; }
  figure { margin: 0 0 .5rem; background: var(--panel); border: 1px solid var(--rule);
           border-radius: 10px; padding: 1.1rem 1.2rem 1rem; overflow-x: auto; }
  figcaption { color: var(--ink-3); font-size: .82rem; margin-top: .7rem; }
  .tiles { display: grid; grid-template-columns: repeat(auto-fit, minmax(9rem, 1fr)); gap: .75rem; }
  .tile { background: var(--panel); border: 1px solid var(--rule); border-radius: 10px; padding: .85rem 1rem; }
  .tile .n { font-size: 1.6rem; font-variant-numeric: tabular-nums; letter-spacing: -.02em; }
  .tile .k { color: var(--ink-3); font-size: .78rem; }
  .legend { display: flex; flex-wrap: wrap; gap: .25rem 1.1rem; margin: .1rem 0 .6rem; font-size: .82rem; color: var(--ink-2); }
  .legend span { display: inline-flex; align-items: center; gap: .4rem; }
  .swatch { width: 11px; height: 11px; border-radius: 3px; display: inline-block; }
  text { font-family: inherit; }
  .tick { fill: var(--ink-3); font-size: 11px; }
  .lbl { fill: var(--ink-2); font-size: 11.5px; }
  .val { fill: var(--ink-2); font-size: 11px; font-variant-numeric: tabular-nums; }
  details { margin: .4rem 0 0; }
  summary { cursor: pointer; color: var(--ink-3); font-size: .82rem; }
  table { border-collapse: collapse; font-size: .8rem; margin-top: .6rem; width: 100%; }
  th, td { text-align: left; padding: .3rem .6rem .3rem 0; border-bottom: 1px solid var(--rule); }
  th { color: var(--ink-3); font-weight: 600; }
  td.num { text-align: right; font-variant-numeric: tabular-nums; }
  .tip { position: fixed; pointer-events: none; background: var(--panel); color: var(--ink);
         border: 1px solid var(--rule); border-radius: 7px; padding: .4rem .6rem; font-size: .8rem;
         box-shadow: 0 6px 20px rgba(0,0,0,.13); opacity: 0; transition: opacity .1s; z-index: 9; }
  .note { border-left: 3px solid var(--s2); padding: .1rem 0 .1rem .9rem; color: var(--ink-2);
          margin: 1rem 0; max-width: 46rem; }
</style>
"""


def render(data: dict, hazards: dict) -> str:
    payload = json.dumps({"data": data, "hazards": hazards}).replace("</", "<\\/")
    env = hazards["environment"]
    goldens = data["golden_sizes"]
    never = [t for t, r in data["branch_coverage"].items() if r["true"] == 0]

    return f"""{HEAD}
<div class="wrap">
<h1>GLOMAP-JAX validation, in pictures</h1>
<p class="sub">Every number here is re-derived from the committed goldens or measured against the
running JAX. Nothing is transcribed. Generated by <code>figures/make_report.py</code>.</p>

<div class="tiles">
  <div class="tile"><div class="n">{len(goldens["archives"])}</div><div class="k">golden archives</div></div>
  <div class="tile"><div class="n">{goldens["total_mb"]:.2f} MB</div><div class="k">of a {goldens["max_total_mb"]:.0f} MB budget</div></div>
  <div class="tile"><div class="n">{len(data["branch_coverage"])}</div><div class="k">branch predicates</div></div>
  <div class="tile"><div class="n" style="color:var(--critical)">{len(never)}</div><div class="k">never exercised</div></div>
</div>

<h2>1 &nbsp;The f32 reference is a different trajectory, not a noisier one</h2>
<p class="lede">Column-scaled gap between the single- and double-precision reference runs, over 24
simulated hours. Three cases sit near 1e-3. <strong>marine_bcoc reaches 0.80</strong> — the same model,
the same namelist, a different answer. This is why <code>ref-f64</code> is the only validation target
(ADR-001).</p>
<figure><div id="fig1"></div>
<figcaption>Peak gap per case. Log scale; each line directly labelled.</figcaption></figure>

<h2>2 &nbsp;Why marine_bcoc diverges: the Aitken insoluble mode</h2>
<p class="lede">Ageing depletes that mode over seven orders of magnitude. In float64 number and mass
leave in proportion and the mean dry diameter holds near 30&nbsp;nm. In float32 the residual loses
significance: the diameter collapses to 5.8&nbsp;nm and the number <em>stops decaying and turns back
up</em>. Two panels, not two y-axes on one.</p>
<figure><div id="fig2"></div>
<figcaption>marine_bcoc, f64 against f32. Left: mean dry diameter. Right: number concentration, log scale.</figcaption></figure>

<div class="note">The branch dump rules out a flipped predicate as the cause: of 108,432 branch
records only 60 differ between the two variants, all from step 45 onward, while the trajectory has
already diverged by step 20. It is cancellation, not a different code path.</div>

<h2>3 &nbsp;What no shipped namelist ever reaches</h2>
<p class="lede">Every predicate the gate-0 dump records, and how often it was true across all four
cases. The bars at zero are the ones with <strong>no reference data at all</strong> — a port could get
them arbitrarily wrong and no trajectory gate would notice. Reaching them is what the constructed
phase-D fixtures are for.</p>
<figure><div id="fig3"></div>
<figcaption>Fraction of records where the predicate was true. Red bars are never-exercised.</figcaption></figure>

<h2>4 &nbsp;Where the obvious spelling gives a different double</h2>
<p class="lede">Fraction of {env["samples"]:,} samples on which the natural JAX spelling disagrees with what
gfortran computes. These are not rounding curiosities — each one cost this port a byte-equality
failure, and two of them were found only after a test had already passed.</p>
<figure><div id="fig4"></div>
<figcaption>Measured on {env["platform"]}, jax {env["jax"]}, numpy {env["numpy"]}. Re-measured on every run:
three of these are version- or platform-dependent.</figcaption></figure>

<div class="note"><strong>Read the last group carefully.</strong> <code>x / 2.0</code> is at zero because
the reciprocal of a power of two is exact, and <code>true_divide</code> is at zero because it is the fix.
Everything between them is a live hazard.</div>

</div>
<div class="tip" id="tip"></div>
<script>
const P = {payload};
const tip = document.getElementById('tip');
const showTip = (e, html) => {{
  tip.innerHTML = html; tip.style.opacity = 1;
  const pad = 14, w = tip.offsetWidth, h = tip.offsetHeight;
  let x = e.clientX + pad, y = e.clientY + pad;
  if (x + w > innerWidth - 8) x = e.clientX - w - pad;
  if (y + h > innerHeight - 8) y = e.clientY - h - pad;
  tip.style.left = x + 'px'; tip.style.top = y + 'px';
}};
const hideTip = () => tip.style.opacity = 0;
const SVG = 'http://www.w3.org/2000/svg';
const el = (n, a = {{}}) => {{ const e = document.createElementNS(SVG, n);
  for (const k in a) e.setAttribute(k, a[k]); return e; }};
const fmt = v => v >= 0.01 ? v.toFixed(3) : v.toExponential(1);

/* ---- 1. precision floor, four log-scale lines ---- */
(function () {{
  const d = P.data.precision_floor, names = Object.keys(d);
  const W = 860, H = 340, L = 64, R = 132, T = 14, B = 40;
  const svg = el('svg', {{viewBox: `0 0 ${{W}} ${{H}}`, width: '100%', role: 'img',
    'aria-label': 'f32 versus f64 trajectory gap per case'}});
  const hrs = d[names[0]].hours, xmax = hrs[hrs.length - 1];
  const lo = -7, hi = 0.2;                       // log10 decades
  const X = h => L + (h / xmax) * (W - L - R);
  const Y = v => T + (1 - (Math.log10(Math.max(v, 1e-9)) - lo) / (hi - lo)) * (H - T - B);
  for (let p = lo + 1; p <= 0; p++) {{
    svg.appendChild(el('line', {{x1: L, x2: W - R, y1: Y(10 ** p), y2: Y(10 ** p),
      stroke: 'var(--grid)', 'stroke-width': 1}}));
    const t = el('text', {{x: L - 8, y: Y(10 ** p) + 4, 'text-anchor': 'end', class: 'tick'}});
    t.textContent = '1e' + p; svg.appendChild(t);
  }}
  for (let h = 0; h <= xmax + .1; h += 6) {{
    const t = el('text', {{x: X(h), y: H - 14, 'text-anchor': 'middle', class: 'tick'}});
    t.textContent = h + 'h'; svg.appendChild(t);
  }}
  names.forEach((n, i) => {{
    const c = `var(--s${{i + 1}})`, g = d[n].gap;
    let path = '';
    g.forEach((v, k) => {{ path += (k ? 'L' : 'M') + X(hrs[k]) + ' ' + Y(v); }});
    svg.appendChild(el('path', {{d: path, fill: 'none', stroke: c, 'stroke-width': 2,
      'stroke-linejoin': 'round', 'stroke-linecap': 'round'}}));
    const lab = el('text', {{x: W - R + 10, y: Y(g[g.length - 1]) + 4, class: 'lbl', fill: c}});
    lab.textContent = n; svg.appendChild(lab);
    const v = el('text', {{x: W - R + 10, y: Y(g[g.length - 1]) + 18, class: 'val'}});
    v.textContent = 'peak ' + fmt(d[n].peak); svg.appendChild(v);
  }});
  hrs.forEach((h, k) => {{
    const hit = el('rect', {{x: X(h) - 6, y: T, width: 12, height: H - T - B, fill: 'transparent'}});
    hit.addEventListener('mousemove', e => showTip(e,
      `<b>${{h.toFixed(1)}} h</b><br>` + names.map((n, i) =>
        `<span style="color:var(--s${{i + 1}})">■</span> ${{n}} ${{fmt(d[n].gap[k])}}`).join('<br>')));
    hit.addEventListener('mouseleave', hideTip);
    svg.appendChild(hit);
  }});
  document.getElementById('fig1').appendChild(svg);
}})();

/* ---- 2. the aitins collapse, two panels ---- */
(function () {{
  const a = P.data.aitins_collapse, hrs = a.hours;
  const host = document.getElementById('fig2');
  const leg = document.createElement('div'); leg.className = 'legend';
  leg.innerHTML = `<span><i class="swatch" style="background:var(--s1)"></i>float64 (the reference)</span>
                   <span><i class="swatch" style="background:var(--s2)"></i>float32</span>`;
  host.appendChild(leg);
  const panels = [
    {{key: 'Ddry_aitins_nm', title: 'mean dry diameter (nm)', log: false}},
    {{key: 'N_aitins_cm3', title: 'number (cm⁻³)', log: true}},
  ];
  const grid = document.createElement('div');
  grid.style.cssText = 'display:grid;grid-template-columns:repeat(auto-fit,minmax(19rem,1fr));gap:1rem';
  panels.forEach(p => {{
    const W = 420, H = 250, L = 56, R = 12, T = 22, B = 34;
    const svg = el('svg', {{viewBox: `0 0 ${{W}} ${{H}}`, width: '100%', role: 'img',
      'aria-label': p.title}});
    const all = a[p.key].f64.concat(a[p.key].f32).filter(v => v > 0);
    const vmax = Math.max(...all), vmin = Math.min(...all);
    const X = h => L + (h / hrs[hrs.length - 1]) * (W - L - R);
    const Y = p.log
      ? v => T + (1 - (Math.log10(Math.max(v, vmin)) - Math.log10(vmin)) /
          (Math.log10(vmax) - Math.log10(vmin))) * (H - T - B)
      : v => T + (1 - v / (vmax * 1.08)) * (H - T - B);
    const ticks = p.log
      ? [vmin, Math.sqrt(vmin * vmax), vmax]
      : [0, vmax / 2, vmax];
    ticks.forEach(v => {{
      svg.appendChild(el('line', {{x1: L, x2: W - R, y1: Y(v), y2: Y(v),
        stroke: 'var(--grid)', 'stroke-width': 1}}));
      const t = el('text', {{x: L - 7, y: Y(v) + 4, 'text-anchor': 'end', class: 'tick'}});
      t.textContent = p.log ? v.toExponential(0) : v.toFixed(0); svg.appendChild(t);
    }});
    const ttl = el('text', {{x: L, y: 12, class: 'lbl'}}); ttl.textContent = p.title;
    svg.appendChild(ttl);
    [['f64', 's1'], ['f32', 's2']].forEach(([k, c]) => {{
      let path = '';
      a[p.key][k].forEach((v, i) => {{ path += (i ? 'L' : 'M') + X(hrs[i]) + ' ' + Y(v); }});
      svg.appendChild(el('path', {{d: path, fill: 'none', stroke: `var(--${{c}})`,
        'stroke-width': 2, 'stroke-linejoin': 'round'}}));
    }});
    for (let h = 0; h <= hrs[hrs.length - 1] + .1; h += 6) {{
      const t = el('text', {{x: X(h), y: H - 12, 'text-anchor': 'middle', class: 'tick'}});
      t.textContent = h + 'h'; svg.appendChild(t);
    }}
    hrs.forEach((h, i) => {{
      const hit = el('rect', {{x: X(h) - 5, y: T, width: 10, height: H - T - B, fill: 'transparent'}});
      hit.addEventListener('mousemove', e => showTip(e,
        `<b>${{h.toFixed(1)}} h</b> · ${{p.title}}<br>
         <span style="color:var(--s1)">■</span> f64 ${{a[p.key].f64[i].toExponential(2)}}<br>
         <span style="color:var(--s2)">■</span> f32 ${{a[p.key].f32[i].toExponential(2)}}`));
      hit.addEventListener('mouseleave', hideTip);
      svg.appendChild(hit);
    }});
    grid.appendChild(svg);
  }});
  host.appendChild(grid);
}})();

/* ---- 3. branch coverage ---- */
(function () {{
  const b = P.data.branch_coverage;
  const rows = Object.entries(b).sort((x, y) => y[1].fraction - x[1].fraction);
  const W = 860, rowH = 21, L = 168, R = 96, T = 8;
  const H = T + rows.length * rowH + 10;
  const svg = el('svg', {{viewBox: `0 0 ${{W}} ${{H}}`, width: '100%', role: 'img',
    'aria-label': 'fraction of records where each branch predicate was true'}});
  rows.forEach(([tag, r], i) => {{
    const y = T + i * rowH, zero = r.true === 0;
    const full = W - L - R;
    svg.appendChild(el('rect', {{x: L, y: y + 4, width: full, height: rowH - 10,
      fill: 'var(--grid)', rx: 3}}));
    const w = Math.max(r.fraction * full, zero ? 0 : 2.5);
    if (w > 0) svg.appendChild(el('rect', {{x: L, y: y + 4, width: w, height: rowH - 10,
      fill: zero ? 'var(--critical)' : 'var(--s1)', rx: 3}}));
    if (zero) svg.appendChild(el('rect', {{x: L, y: y + 4, width: 4, height: rowH - 10,
      fill: 'var(--critical)', rx: 2}}));
    const t = el('text', {{x: L - 9, y: y + rowH / 2 + 3, 'text-anchor': 'end', class: 'lbl'}});
    t.textContent = tag; svg.appendChild(t);
    const v = el('text', {{x: W - R + 8, y: y + rowH / 2 + 3, class: 'val'}});
    v.textContent = zero ? 'never reached' : (r.fraction * 100).toFixed(0) + '%';
    if (zero) v.setAttribute('fill', 'var(--critical)');
    svg.appendChild(v);
    const hit = el('rect', {{x: 0, y: y, width: W, height: rowH, fill: 'transparent'}});
    hit.addEventListener('mousemove', e => showTip(e,
      `<b>${{tag}}</b><br>${{r.true.toLocaleString()}} true of ${{r.records.toLocaleString()}} records`));
    hit.addEventListener('mouseleave', hideTip);
    svg.appendChild(hit);
  }});
  document.getElementById('fig3').appendChild(svg);
}})();

/* ---- 4. numerical hazards ---- */
(function () {{
  const h = P.hazards;
  const groups = [
    ['FMA contraction (under jit)', h.fma_contraction],
    ['integer literal exponents', h.integer_powers],
    ['compat layer', h.cbrt_and_rounding],
    ['division by a scalar constant', h.division_rewrite],
  ];
  const rows = [];
  groups.forEach(([g, obj]) => Object.entries(obj).forEach(([k, v]) => rows.push([g, k, v])));
  const W = 860, rowH = 22, L = 210, R = 66, T = 8, gapH = 16;
  let H = T + 10;
  let last = null;
  rows.forEach(([g]) => {{ if (g !== last) {{ H += gapH; last = g; }} H += rowH; }});
  const svg = el('svg', {{viewBox: `0 0 ${{W}} ${{H}}`, width: '100%', role: 'img',
    'aria-label': 'fraction of samples where the JAX spelling differs from gfortran'}});
  let y = T; last = null;
  rows.forEach(([g, k, v]) => {{
    if (g !== last) {{
      const t = el('text', {{x: 0, y: y + 12, class: 'tick'}});
      t.textContent = g.toUpperCase(); t.setAttribute('letter-spacing', '.06em');
      svg.appendChild(t); y += gapH; last = g;
    }}
    const full = W - L - R;
    svg.appendChild(el('rect', {{x: L, y: y + 4, width: full, height: rowH - 10,
      fill: 'var(--grid)', rx: 3}}));
    const safe = v === 0;
    if (v > 0) svg.appendChild(el('rect', {{x: L, y: y + 4, width: Math.max(v * full, 2.5),
      height: rowH - 10, fill: 'var(--s2)', rx: 3}}));
    else svg.appendChild(el('rect', {{x: L, y: y + 4, width: 4, height: rowH - 10,
      fill: 'var(--good)', rx: 2}}));
    const t = el('text', {{x: L - 9, y: y + rowH / 2 + 3, 'text-anchor': 'end', class: 'lbl'}});
    t.textContent = k; svg.appendChild(t);
    const val = el('text', {{x: W - R + 8, y: y + rowH / 2 + 3, class: 'val'}});
    val.textContent = safe ? 'identical' : (v * 100).toFixed(1) + '%';
    if (safe) val.setAttribute('fill', 'var(--good)');
    svg.appendChild(val);
    const hit = el('rect', {{x: 0, y: y, width: W, height: rowH, fill: 'transparent'}});
    hit.addEventListener('mousemove', e => showTip(e, `<b>${{k}}</b><br>` +
      (safe ? 'bit-identical on every sample' :
        (v * 100).toFixed(1) + '% of ' + P.hazards.environment.samples.toLocaleString() + ' samples differ')));
    hit.addEventListener('mouseleave', hideTip);
    svg.appendChild(hit);
    y += rowH;
  }});
  document.getElementById('fig4').appendChild(svg);
}})();
</script>
"""


def main() -> int:
    data = json.loads((HERE / "data.json").read_text(encoding="utf-8"))
    hazards = json.loads((HERE / "hazards.json").read_text(encoding="utf-8"))
    OUT.write_text(render(data, hazards), encoding="utf-8")
    print(f"wrote {OUT.name} ({OUT.stat().st_size / 1e3:.0f} kB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
