#!/usr/bin/env python3
"""Extract `ukca_vapour.F90`'s PARAMETERs and lookup tables.

    python validation/extract_vapour_literals.py           # regenerate
    python validation/extract_vapour_literals.py --check   # exit 1 if stale

Writes `src/glomap_jax/physics/_vapour_literals.py`. Generated, committed, and
verified by `tests/test_vapour.py`.

The Ayers fit coefficients (`ks1`..`ks7`) and the three twelve-entry
stratospheric density tables are the whole numerical content of this routine.
`ks4 = -15732.0` in particular sits inside `b = ks3 + ks4*ust`, whose root is
the cancellation point at T = 303.6479444122756 K where `xsb`'s numerator and
denominator both collapse -- so a mistyped digit there does not give a slightly
different answer, it moves a pole.

Only the constants the **live** path uses are emitted. `surften` is deliberately
excluded: it feeds `term1`, `kelvin` and `kelvin_out`, none of which reach an
`INTENT(OUT)`. See `physics/vapour.py` for the dead-chain analysis.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SOURCE = REPO / "fortran" / "src" / "ukca" / "ukca_vapour.F90"
TARGET = REPO / "src" / "glomap_jax" / "physics" / "_vapour_literals.py"

# Scalars on the live path only. surften/rmol/rho_so4/mmsul are omitted because
# the chain they feed is dead; that is asserted in tests/test_vapour.py rather
# than left as a comment.
SCALARS = (
    "xsb_eps",
    "p0",
    "ks1",
    "ks2",
    "ks3",
    "ks4",
    "ks5",
    "ks6",
    "ks7",
    "bminatm",
    "bmaxatm",
)
TABLES = ("percent", "k_diff", "data253")


def _fortran_real(token: str) -> float:
    return float(token.strip().replace("d", "e").replace("D", "E"))


def _scalar(text: str, name: str) -> float:
    pattern = re.compile(rf"^\s*(?:INTEGER|REAL)[^:]*::\s*{name}\s*=\s*([^\s!]+)\s*$", re.MULTILINE)
    found = pattern.findall(text)
    if len(found) != 1:
        raise SystemExit(f"{name}: expected one PARAMETER declaration, found {len(found)}")
    return _fortran_real(found[0])


def _table(text: str, name: str) -> list[float]:
    pattern = re.compile(
        rf"(?:INTEGER|REAL),\s*PARAMETER\s*::\s*{name}\(ndata\)\s*=\s*&?\s*\[(.*?)\]",
        re.DOTALL,
    )
    found = pattern.findall(text)
    if len(found) != 1:
        raise SystemExit(f"{name}: expected one table declaration, found {len(found)}")
    body = re.sub(r"&\s*\n\s*", "", found[0])
    values = [_fortran_real(v) for v in body.split(",")]
    if len(values) != 12:
        raise SystemExit(f"{name}: expected ndata = 12 entries, parsed {len(values)}")
    return values


def extract(text: str | None = None) -> dict:
    text = SOURCE.read_text(encoding="utf-8") if text is None else text
    data = {"scalars": {n: _scalar(text, n) for n in SCALARS}}
    data["tables"] = {n: _table(text, n) for n in TABLES}

    ndata = re.findall(r"INTEGER,\s*PARAMETER\s*::\s*ndata\s*=\s*(\d+)", text)
    if ndata != ["12"]:
        raise SystemExit(f"ndata is {ndata}, expected exactly one declaration of 12")

    # The lookup at :233 matches `round` against `percent`, so a duplicate entry
    # would make the last match win silently.
    percent = data["tables"]["percent"]
    if len(set(percent)) != len(percent):
        raise SystemExit(f"percent has duplicate entries: {percent}")
    return data


def _display(path: Path) -> str:
    try:
        return str(path.relative_to(REPO))
    except ValueError:
        return str(path)


def render(data: dict) -> str:
    lines = [
        '"""Generated by `validation/extract_vapour_literals.py`. Do not edit.',
        "",
        "`ukca_vapour.F90`'s PARAMETERs, live path only. The Ayers fit",
        "coefficients and the three stratospheric density tables.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
    ]
    for name in SCALARS:
        lines.append(f"{name.upper()} = {data['scalars'][name]!r}")
    lines.append("")
    lines.append("# Weight-percent H2SO4 the density table is tabulated at (:90).")
    lines.append(f"PERCENT = {tuple(int(v) for v in data['tables']['percent'])!r}")
    lines.append("")
    lines.append("# Density at 253 K, kg m-3 (:98), and its per-Kelvin slope (:94).")
    # Wrapped one-per-line: twelve four-figure reals do not fit in 100 columns,
    # and the generated file is linted and formatted like any other, so an
    # unwrapped tuple would make `--check` disagree with the file on disk the
    # moment `ruff format` touched it.
    for name, key in (("DATA253", "data253"), ("K_DIFF", "k_diff")):
        lines.append(f"{name} = (")
        for value in data["tables"][key]:
            lines.append(f"    {value!r},")
        lines.append(")")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if the file is stale")
    args = parser.parse_args(argv)

    fresh = extract()
    if args.check:
        if not TARGET.is_file():
            print(f"{_display(TARGET)} does not exist; generate it")
            return 1
        if TARGET.read_text(encoding="utf-8") != render(fresh):
            print(f"{_display(TARGET)} disagrees with the Fortran; regenerate it")
            return 1
        print(f"{_display(TARGET)} is up to date")
        return 0

    TARGET.write_text(render(fresh), encoding="utf-8")
    print(f"wrote {_display(TARGET)} ({len(SCALARS)} scalars, {len(TABLES)} tables)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
