#!/usr/bin/env python3
"""Extract `ukca_remode`'s 19 merge budget write sites into a generated table.

    python validation/extract_remode_literals.py --check
    python validation/extract_remode_literals.py

Each site is `bud_aer_mas(jl,NAME) = bud_aer_mas(jl,NAME) + dm(icp)` guarded on
`(icp == cp_XX) .AND. (NAME > 0)` inside an `imode ==` block. The name encodes
both: `nmasmergsuintr12` is `su`, mode 1 -> mode 2, and the parse asserts the
suffix against the block it sits in, since a mismatch would bank one mode's
merged mass against another's diagnostic.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SOURCE = REPO / "fortran" / "src" / "ukca" / "ukca_remode.F90"
TARGET = REPO / "src" / "glomap_jax" / "physics" / "_remode_literals.py"

MODE_INDEX = {"mode_nuc_sol": 1, "mode_ait_sol": 2, "mode_acc_sol": 3, "mode_cor_sol": 4}
CP_INDEX = {
    "cp_su": 1,
    "cp_bc": 2,
    "cp_oc": 3,
    "cp_cl": 4,
    "cp_du": 5,
    "cp_so": 6,
    "cp_nh4": 7,
    "cp_no3": 8,
    "cp_nn": 9,
    "cp_mp": 10,
}
TAG_TO_CP = {
    "su": "cp_su",
    "bc": "cp_bc",
    "oc": "cp_oc",
    "ss": "cp_cl",
    "du": "cp_du",
    "so": "cp_so",
    "nh": "cp_nh4",
    "nt": "cp_no3",
    "nn": "cp_nn",
    "mp": "cp_mp",
}

_BLOCK = re.compile(r"IF\(imode==(mode_\w+)\)THEN")
_SITE = re.compile(
    r"IF\(\(icp==(cp_\w+)\)\.AND\.\((nmasmerg\w+)>0\)\)"
    r"bud_aer_mas\(jl,\2\)=bud_aer_mas\(jl,\2\)\+dm\(icp\)"
)
_NAME = re.compile(r"^nmasmerg([a-z0-9]+?)intr(\d)(\d)$")


def build() -> dict:
    text = SOURCE.read_text(encoding="utf-8")
    text = re.sub(r"&\s*\n\s*", "", text)
    text = re.sub(r"!.*", "", text)
    body = re.sub(r"\s+", "", text)

    blocks = [
        (m.start(), MODE_INDEX[m.group(1)])
        for m in _BLOCK.finditer(body)
        if m.group(1) in MODE_INDEX
    ]
    rows: list[tuple[int, int, int, str]] = []
    for m in _SITE.finditer(body):
        icp_name, budget = m.groups()
        enclosing = [b for b in blocks if b[0] < m.start()]
        if not enclosing:
            raise SystemExit(f"{budget} sits outside every `imode ==` block")
        imode = enclosing[-1][1]
        nm = _NAME.match(budget)
        if not nm:
            raise SystemExit(f"{budget} does not match nmasmerg<cp>intr<i><j>")
        tag, ni, nj = nm.group(1), int(nm.group(2)), int(nm.group(3))
        if TAG_TO_CP.get(tag) != icp_name:
            raise SystemExit(f"{budget} encodes {tag!r} but guards on {icp_name}")
        if (ni, nj) != (imode, imode + 1):
            raise SystemExit(
                f"{budget} says {ni}->{nj} but sits in the mode {imode} block, which "
                f"merges into {imode + 1}"
            )
        rows.append((imode, imode + 1, CP_INDEX[icp_name], budget))

    if len({r[3] for r in rows}) != len(rows):
        raise SystemExit("a merge budget name appears at more than one site")
    if not rows:
        raise SystemExit("no merge budget sites parsed")
    return {"rows": rows}


def render(data: dict) -> str:
    lines = [
        '"""Generated by `validation/extract_remode_literals.py`. Do not edit.',
        "",
        "`ukca_remode`'s merge budget write sites, one row each:",
        "",
        "    (imode, jmode, icp, budget)   all 1-based; jmode is always imode+1",
        "",
        "The extractor asserts each name's `intr<i><j>` suffix and component tag",
        "against the `imode ==` block it sits in.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "#: (imode, jmode, icp, budget), in source order.",
        "MERGE_BUDGET_SITES = (",
    ]
    for imode, jmode, icp, budget in data["rows"]:
        lines.append(f'    ({imode}, {jmode}, {icp}, "{budget}"),')
    lines += [")", ""]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    fresh = render(build())
    if args.check:
        if not TARGET.is_file():
            print(f"{TARGET} does not exist; run without --check", file=sys.stderr)
            return 1
        if TARGET.read_text(encoding="utf-8") != fresh:
            print(f"{TARGET} is stale; re-run without --check", file=sys.stderr)
            return 1
        print(f"{TARGET.name} is up to date")
        return 0
    TARGET.write_text(fresh, encoding="utf-8")
    print(f"wrote {TARGET} -- {len(build()['rows'])} write sites")
    return 0


if __name__ == "__main__":
    sys.exit(main())
