#!/usr/bin/env python3
"""Extract `ukca_ageing`'s 21 budget write sites into a generated table.

    python validation/extract_ageing_literals.py --check
    python validation/extract_ageing_literals.py

Each site is one guarded accumulation, and there are two kinds::

    bud_aer_mas(jl,NAME) = bud_aer_mas(jl,NAME) + totage(icp)*f_mm(icp)
    bud_aer_mas(jl,NAME) = bud_aer_mas(jl,NAME) + naged*md(jl,imode,icp)

The first banks the soluble material that condensed or coagulated onto the
insoluble mode, converted back into aerosol-component units by `f_mm`. The
second banks the insoluble mode's own mass, carried across with the particles.
21 sites, 20 distinct names -- `nmasagedocintr52` takes **both**, because
organic carbon is a condensable *and* a primary insoluble component, and the
two contributions are different quantities rather than a duplication like
issue #29's.

The parse asserts the name against its guard: `nmasagedsuintr52` is `su`, mode
5 -> mode 2, and `tmode` must equal `imode - 3` (or `imode - 4` at
`mode_sup_insol`). A site whose suffix disagreed with the block it sits in
would bank one transfer against another's diagnostic.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SOURCE = REPO / "fortran" / "src" / "ukca" / "ukca_ageing.F90"
TARGET = REPO / "src" / "glomap_jax" / "physics" / "_ageing_literals.py"

CP_INDEX = {
    "cp_su": 1,
    "cp_bc": 2,
    "cp_oc": 3,
    "cp_cl": 4,
    "cp_du": 5,
    "cp_so": 6,
    "cp_nh4": 7,
    "cp_no3": 8,
    "cp_nn": 9,
    "cp_mp": 10,
}
TAG_TO_CP = {
    "su": "cp_su",
    "bc": "cp_bc",
    "oc": "cp_oc",
    "ss": "cp_cl",
    "du": "cp_du",
    "so": "cp_so",
    "nh": "cp_nh4",
    "nt": "cp_no3",
    "nn": "cp_nn",
    "mp": "cp_mp",
}

_SITE = re.compile(
    r"IF\(\(icp==(cp_\w+)\)\.AND\.\((nmasaged\w+)>0\)\)THEN"
    r"bud_aer_mas\(jl,\2\)=bud_aer_mas\(jl,\2\)\+"
    r"(totage\(icp\)\*f_mm\(icp\)|naged\*md\(jl,imode,icp\))"
)
_NAME = re.compile(r"^nmasaged([a-z0-9]+?)intr(\d)(\d)$")


def build() -> dict:
    text = SOURCE.read_text(encoding="utf-8")
    text = re.sub(r"&\s*\n\s*", "", text)
    text = re.sub(r"!.*", "", text)
    body = re.sub(r"\s+", "", text)

    rows: list[tuple[int, int, int, str, str]] = []
    for m in _SITE.finditer(body):
        icp_name, budget, expr = m.groups()
        name_match = _NAME.match(budget)
        if not name_match:
            raise SystemExit(f"{budget} does not match nmasaged<cp>intr<i><t>")
        tag, imode, tmode = name_match.group(1), int(name_match.group(2)), int(name_match.group(3))
        if tag not in TAG_TO_CP:
            raise SystemExit(f"{budget} carries an unknown component tag {tag!r}")
        if TAG_TO_CP[tag] != icp_name:
            raise SystemExit(f"{budget} encodes {tag!r} but guards on {icp_name}")
        expected_t = imode - 3 if imode < 8 else imode - 4
        if tmode != expected_t:
            raise SystemExit(
                f"{budget} says {imode}->{tmode} but ukca_ageing.F90:219-223 sends "
                f"mode {imode} to mode {expected_t}"
            )
        kind = "totage" if expr.startswith("totage") else "naged"
        rows.append((imode, tmode, CP_INDEX[icp_name], budget, kind))

    if len(rows) != 21:
        raise SystemExit(f"{len(rows)} write sites parsed, expected 21")
    names = [r[3] for r in rows]
    twice = sorted({n for n in names if names.count(n) > 1})
    if twice != ["nmasagedocintr52"]:
        raise SystemExit(f"names written twice are {twice}, expected only nmasagedocintr52")
    for name in twice:
        kinds = sorted({r[4] for r in rows if r[3] == name})
        if kinds != ["naged", "totage"]:
            raise SystemExit(f"{name} is written twice with kinds {kinds}, not one of each")
    return {"rows": rows}


def render(data: dict) -> str:
    lines = [
        '"""Generated by `validation/extract_ageing_literals.py`. Do not edit.',
        "",
        "`ukca_ageing`'s 21 budget write sites, parsed out of the Fortran.",
        "",
        "    (imode, tmode, icp, budget, kind)   all 1-based",
        "",
        "`kind` is `totage` for `totage(icp)*f_mm(icp)` -- the soluble material that",
        "condensed or coagulated onto the insoluble mode -- and `naged` for",
        "`naged*md(jl,imode,icp)`, the insoluble mode's own mass travelling with the",
        "particles. 21 sites, 20 distinct names: `nmasagedocintr52` takes both,",
        "because organic carbon is a condensable and a primary insoluble component.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "#: (imode, tmode, icp, budget, kind), in source order.",
        "AGEING_BUDGET_SITES = (",
    ]
    for imode, tmode, icp, budget, kind in data["rows"]:
        lines.append(f'    ({imode}, {tmode}, {icp}, "{budget}", "{kind}"),')
    lines += [")", ""]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    fresh = render(build())
    if args.check:
        if not TARGET.is_file():
            print(f"{TARGET} does not exist; run without --check", file=sys.stderr)
            return 1
        if TARGET.read_text(encoding="utf-8") != fresh:
            print(f"{TARGET} is stale; re-run without --check", file=sys.stderr)
            return 1
        print(f"{TARGET.name} is up to date")
        return 0
    TARGET.write_text(fresh, encoding="utf-8")
    print(f"wrote {TARGET} -- {len(build()['rows'])} write sites")
    return 0


if __name__ == "__main__":
    sys.exit(main())
